remove all references to atom or atom community
pulsar-edit/pulsar pull request #11
Opened 2022-08-07 21:01 UTC by stech11845

In README at least.

2022-08-07 21:17 UTC, confused-Techie requested changes
This looks great, I've added one change I think we should fix while here, but otherwise appreciate the contribution!

2022-08-07 21:17 UTC, confused-Techie commented on README.md
> +[Discord]: https://discord.gg/2tD9evh8qP 'Join the Pulsar Discord today!'
May be a good idea here to add the proper link to the Pulsar Edit Discord server `https://discord.gg/7aEbB9dGRT`

2022-08-07 21:26 UTC, autumnblazey commented on README.md
> +[Discord]: https://discord.gg/2tD9evh8qP 'Join the Pulsar Discord today!'
oh yea, that current invite is to atom community's server

2022-08-07 21:41 UTC, stech11845 commented on README.md
> +[Discord]: https://discord.gg/2tD9evh8qP 'Join the Pulsar Discord today!'
> oh yea, that current invite is to atom community's server

I guess someone should make a Discord, or else we will point people to Atom Community's server.

2022-08-07 22:15 UTC, confused-Techie approved these changes
Thanks for adding the changes! But this looks great to me, while its on Pulsar, since its the readme I'll ping our @pulsar-edit/documentation team to get some additional feedback on what they think. Super rad work!

2022-08-07 23:39 UTC, autumnblazey reviewed
hmm, the logo guidelines will need to be updated/removed (since we are not GitHub), and CI will need to be updated once we have working CI again (as per #12), but otherwise I think it looks good!

2022-08-07 23:39 UTC, autumnblazey approved these changes

2022-08-08 04:19 UTC, stech11845 commented
> he logo guidelines will need to be updated/removed (since we are not GitHub)

**requires:** a new logo.

2022-08-08 04:35 UTC, autumnblazey commented
hehe, I think progress is actually being made on that c:

2022-08-08 04:40 UTC, confused-Techie commented
So how do we feel about merging this one as is, then once builds are sorted we could modify as needed, and hopefully once the artist being worked with is sorted (or alternative method) we could update that. Since really I'm happy with incremental changes even if we miss a couple things, as long as we know about them

2022-08-09 05:05 UTC, stech11845 commented
> So how do we feel about merging this one as is, then once builds are sorted we could modify as needed, and hopefully once the artist being worked with is sorted (or alternative method) we could update that. Since really I'm happy with incremental changes even if we miss a couple things, as long as we know about them

Ok.

2022-08-18 23:43 UTC, merged