Update help links
pulsar-edit/pulsar pull request #145
Opened 2022-11-16 15:37 UTC by Daeraxa

Various links in `Help` lead to Atom areas.
This updates them to various areas of the website, GitHub discussions + issues etc.

2022-11-17 00:30 UTC, confused-Techie requested changes
Overall this looks great, just pointed out some areas I feel like should be changed.

2022-11-17 00:30 UTC, confused-Techie commented on packages/welcome/lib/welcome-view.js
> +                  href="https://github.com/orgs/pulsar-edit/discussions"
```suggestion
                  href="https://github.com/orgs/pulsar-edit/discussions"
```

Personally still feel like this should link to our ORG wide discussion. Which if I recall correctly, is using the Pulsar discussions

2022-11-17 00:30 UTC, confused-Techie commented on src/main-process/atom-application.js
> +      shell.openExternal('https://github.com/orgs/pulsar-edit/discussions')
Again here, feel like it should be the org discussions.

2022-11-17 00:43 UTC, Daeraxa commented on packages/welcome/lib/welcome-view.js
> +                  href="https://github.com/orgs/pulsar-edit/discussions"
I'm not sure I understand, that suggested change is the same as what I've put isn't it?
![image](https://user-images.githubusercontent.com/58074586/202326024-97c4efc7-3c98-45ba-8672-7fa4a5227394.png)

2022-11-17 00:43 UTC, Daeraxa commented on src/main-process/atom-application.js
> +      shell.openExternal('https://github.com/orgs/pulsar-edit/discussions')
Same as above? That is our URL isn't it?

2022-11-17 00:54 UTC, Daeraxa commented
Actually realised I should be using the brandurl, I'll update it

2022-11-17 07:02 UTC, confused-Techie commented on packages/welcome/lib/welcome-view.js
> +                  href="https://github.com/orgs/pulsar-edit/discussions"
Apparently I've been staring at a screen for to long today. My bad

2022-11-17 07:22 UTC, confused-Techie approved these changes
This looks great to me!

2022-11-17 11:05 UTC, Sertonix commented on packages/welcome/lib/welcome-view.js
> +                  href="https://github.com/orgs/pulsar-edit/discussions"
Could you use a new branding url here like `atom.branding.urlDiscussions`?

2022-11-17 11:33 UTC, Daeraxa commented on packages/welcome/lib/welcome-view.js
> +                  href="https://github.com/orgs/pulsar-edit/discussions"
Can do if we think it is worth it

2022-11-20 04:49 UTC, confused-Techie commented
Tests are passing how we would expect, and since this is mostly a change of the text and not code itself, I'll go ahead and merge. Thanks for the contribution!

2022-11-20 04:49 UTC, merged