Bump GitHub package
pulsar-edit/pulsar pull request #186
Opened 2022-12-01 15:14 UTC by mauricioszabo

2022-12-02 00:54 UTC, confused-Techie approved these changes
This looks great to me and is an important update. Love seeing the ChangeLog being updated,

But otherwise do we have to keep the `0.36.12-fix`? Looks like a regular tag was also generated on [`github`](https://github.com/pulsar-edit/github/releases/tag/v0.36.12)

2022-12-04 01:03 UTC, confused-Techie requested changes
Hope that this new version improves things, which it seems that it is at least slightly. Just gotta keep the rest of it up to date with these new changes, then I say lets merge

2022-12-04 01:03 UTC, confused-Techie commented on CHANGELOG.md
> +- Bump github package to 0.36.12 (add Silicon Apple support)
```suggestion
- Bump github package to 0.36.13 (add Silicon Apple support)
```

2022-12-04 01:03 UTC, confused-Techie commented on package.json
> +    "github": "0.36.12",
```suggestion
    "github": "0.36.13",
```

2022-12-10 13:08 UTC, benonymus commented
Is anything blocking this pr in particular?

2022-12-10 22:28 UTC, confused-Techie commented
> Is anything blocking this pr in particular?

So this PR is essentially valid, but due to having to technically bump twice over the course of this PR, some of the other details are inaccurate as you can see in my review comments. 

Suppose we haven't gotten around to fixing those yet, but I may just commit my comments myself, and take a look at the tests how things are going.

I think the PR lost some steam since it didn't totally fix the issues we saw, but still wouldn't be bad to at least include another bump in here

2022-12-11 00:08 UTC, benonymus commented
> > Is anything blocking this pr in particular?
> 
> So this PR is essentially valid, but due to having to technically bump twice over the course of this PR, some of the other details are inaccurate as you can see in my review comments.
> 
> Suppose we haven't gotten around to fixing those yet, but I may just commit my comments myself, and take a look at the tests how things are going.
> 
> I think the PR lost some steam since it didn't totally fix the issues we saw, but still wouldn't be bad to at least include another bump in here

What does it not fix? 

As far as I remember the only reason for the bump was to get to a version that supports apple silicon.
Which this version should do.
I have been using the apple silicon build form here: https://github.com/pulsar-edit/pulsar/pull/124 
for the last month every day without any issue.

2022-12-11 00:58 UTC, confused-Techie commented
> 
> What does it not fix?
> 

Performance Issues mainly, but yeah fair enough it does tackle the main reason it was created. I'll go ahead and apply the reviews manually, and merge this one.

2022-12-11 02:32 UTC, confused-Techie approved these changes
The tests here look good, and like previously stated this adds support for Apple Silicon, I'll go ahead and merge

2022-12-11 02:32 UTC, merged