Incorporate settings-view into Pulsar repo
pulsar-edit/pulsar pull request #214
Opened 2022-12-12 22:30 UTC by Daeraxa

This PR aims to move [settings-view](https://github.com/pulsar-edit/settings-view) into the main repo as part of the work to move more core packages in as [per Discord convo](https://discord.com/channels/992103415163396136/1050238039915507742/1050924605780545557).

The original reason this was not done in the initial work by the Atom team was because of "too many open PRs".

There were a couple of PRs on the repo. For this PR I've incorporated `#9` and `#18` by @Sertonix as they have comments or other acceptance to being merged from similar PRs. Please check out https://github.com/pulsar-edit/settings-view/pull/18 and https://github.com/pulsar-edit/settings-view/pull/9 for conversation and diff.

There are still two more active PRs by @jonian which have not received comment so I'm proposing that, if this is agreed and merged, those PRs should be made on this repo instead.

I've also done some rebranding/docs linking on the readme.

2022-12-13 00:42 UTC, confused-Techie requested changes
This overall looks really good but I'd suggest we remove the `.github` folder in this package, and make sure to modify the `packageDependencies` entry for settings view if it exists.

Otherwise fantastic PR

2022-12-13 03:11 UTC, Daeraxa commented
Forgot about the packageDependencies, good spot. That has been updated now along with the removal of .github.

2022-12-13 03:26 UTC, confused-Techie approved these changes
This looks fantastic, lets go ahead and merge!

2022-12-13 06:49 UTC, Sertonix commented on packages/settings-view/package-lock.json
> +  "lockfileVersion": 2,
Can you update this with `npm i --package-lock-only`? I think the last version is `3`

2022-12-13 08:14 UTC, Sertonix commented on packages/settings-view/CONTRIBUTING.md
> +[See how you can contribute](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md)
Could you remove this file?

2022-12-13 08:15 UTC, Sertonix commented on packages/settings-view/README.md
> +MIT License.  See [the license](../../LICENSE.md) for more details.
Good Idea but since this file will be displayd in the settings-view it will cause problems.

2022-12-13 08:44 UTC, confused-Techie commented on packages/settings-view/README.md
> +MIT License.  See [the license](../../LICENSE.md) for more details.
```suggestion
MIT License.  See [the license](https://github.com/pulsar-edit/pulsar/blob/master/LICENSE.md) for more details.
```

You do have a point, once the app is bundled into an ASAR archive, this path likely won't resolve.

Maybe we could just link to the same document but onto the GitHub Website?

2022-12-13 16:00 UTC, Daeraxa commented on packages/settings-view/README.md
> +MIT License.  See [the license](../../LICENSE.md) for more details.
Yeah good point, forgot about it showing within Pulsar.

2022-12-13 16:00 UTC, Daeraxa commented on packages/settings-view/CONTRIBUTING.md
> +[See how you can contribute](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md)
Is there a reason to remove it?

2022-12-13 16:09 UTC, Daeraxa commented on packages/settings-view/CONTRIBUTING.md
> +[See how you can contribute](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md)
Yes I get that but I meant more from prior examples. So it does indeed seem this file isn't present in other core packages so that makes sense to remove it.

2022-12-14 01:41 UTC, Daeraxa commented
Any idea what I did wrong to make Cirrus explode?

2022-12-14 01:43 UTC, closed without merging

2022-12-14 01:45 UTC, Daeraxa commented
Sorry, messed up with GH CLI... please hold...