Initial Rebrand Effort (rebased to master)
pulsar-edit/pulsar pull request #22
Opened 2022-08-17 04:26 UTC by mauricioszabo

Rebase of PR https://github.com/pulsar-edit/pulsar/pull/21 - original message below:

Large PR - Individual commits per associated segment

Rebrand all of the non-api/non-variable/non-github link instances of Atom or atom to Pulsar or pulsar respectively

Current build commands

nvm install 16.16.0 #May not be needed
npm install --location=global yarn
yarn install
yarn build
yarn build:apm #Not strictly necessary
yarn start
Known bugs as of initial PR:

GitHub renderer.html/renderer.js require is not defined
Tree-sitter is an incompatible version. It wants 13, gets 10
Settings-View package-manager fails to fetch local or outdated packages/themes - This is presumed to be a problematic interaction with apm. Apm expects files to be in a .atom directory, which is no longer the case.

2022-08-17 13:38 UTC, Spiker985 requested changes
Requested updates to review `dot-atom` -> `templates`

2022-08-17 13:38 UTC, Spiker985 commented on src/main-process/atom-application.js
> +      const templateConfigDirPath = fs.resolve(this.resourcePath, 'templates');
```suggestion
      const templateConfigDirPath = fs.resolve(this.resourcePath, 'dot-atom');
```
I had renamed dot-atom to templates to make it more concise as to what it was supposed to be, however, that doesn't belong in this PR.

We can revert this line

2022-08-17 13:38 UTC, Spiker985 commented on templates/.gitignore
> +.pulsar-socket-secret-*
We'll need to revert the folder rename in this commit, but keep the file content changes

2022-08-17 13:38 UTC, Spiker985 commented on script/lib/copy-assets.js
> +    path.join(CONFIG.repositoryRootPath, 'templates'),
```suggestion
    path.join(CONFIG.repositoryRootPath, 'dot-atom'),
```
Revert this line to coincide with reverting templates -> dot-atom

2022-08-17 13:38 UTC, Spiker985 commented on script/lib/lint-coffee-script-paths.js
> +    path.join(CONFIG.repositoryRootPath, 'templates/**/*.coffee'),
```suggestion
    path.join(CONFIG.repositoryRootPath, 'dot-atom/**/*.coffee'),
```
Revert this line to coincide with reverting templates -> dot-atom

2022-08-17 13:38 UTC, Spiker985 commented on script/electron-builder.js
> +const path = require('path')
This was accidentally pulled in from another branch during an errant rebase and should not be part of this PR. Apologies

2022-08-17 13:38 UTC, Spiker985 commented on src/protocol-handler-installer.js
> +          'Pulsar is not currently set as the default handler for atom:// URIs. Would you like Atom to handle ' +
```suggestion
          'Pulsar is not currently set as the default handler for atom:// URIs. Would you like Pulsar to handle ' +
```

2022-08-17 15:25 UTC, Spiker985 commented on script/electron-builder.js
> +const path = require('path')
We decided that this script can stay as of now, as it won't make a difference at this moment, is up to date, and is expected to be required later

2022-09-10 23:08 UTC, softcode589 commented on Dockerfile
> +COPY . /pulsar
Why is the dockerfile being changed? This is a full rebrand effort. I know about the copy and workdir being changed to pulsar, but we could have some npm packages being maintained.

2022-09-13 00:15 UTC, confused-Techie approved these changes
This PR has been sitting open for quite some time. But many of the commits on this one I helped author, (or slightly edit really). But otherwise this looks good to me and I'll approve. 

This finally gets all the fantastic rebrand efforts over to master, so hopefully we could have a rebranding build from cirrus? @mauricioszabo 

But otherwise lets try to get a few more eyes on this, as well as some issues open on this PR @pulsar-edit/core

2022-09-16 19:14 UTC, kaosine approved these changes
This seems to be mostly right, and I'd recommend merging it, so we can merge the e12 one as well. Though do wish we could make the pulsar mentions more generic in the code so that anyone could fork and use this in their own projects. But I'd be happy to just get this done and gone, so we can move forward.

2022-09-16 22:18 UTC, merged