Made changes to the main.js file. Setting a new path for pulsar.(for the forth time time, my god!)
pulsar-edit/pulsar pull request #232
Opened 2022-12-15 03:09 UTC by CatPerson136

Made some changes to the main JS file to fix the paths just in case for a new feature would need that.

2022-12-15 03:31 UTC, confused-Techie commented
@CatPerson136 this looks perfect now, thanks for working through those issues. We will review this as soon as possible

2022-12-15 03:46 UTC, DeeDeeG commented
#### Background, as I understand it:

So, way back when, the Atom folks kind of loosely assumed (and suggested) that you would clone Atom to [your home] / github / atom.

This helps dev mode work by default. (Dev mode loads almost all files from the source files on disk, rather than the bundled application if there is one.)

(Otherwise, people would have to specify an `ATOM_DEV_RESOURCE_PATH=` environment variable, or an `-r`/`--resource-path` CLI argument to point the editor to the source files.)

---

#### This PR:

So, this PR assumes/suggests users clone to [your home]/pulsar-edit/pulsar instead of [your home]/github/atom.

My thoughts: Seems like an improvement, I suppose. We can maybe bikeshed what the path should be, but that's as reasonable a path as any, I suppose? Also, I'm not sure how the state of Dev Mode is in Pulsar, since I haven't tried using it in a while. But yeah, this seems to be a reasonable thing to update now that we've re-branded.

2022-12-17 19:08 UTC, CatPerson136 commented
Hello how is everyone.

2022-12-19 16:56 UTC, Spiker985 requested changes

2022-12-19 16:56 UTC, Spiker985 commented on src/main-process/main.js
> +    app.getPath('home','pulsar-edit','pulsar')
```suggestion
    app.getPath('home'),
    'pulsar-edit',
    'pulsar'
```
https://www.electronjs.org/docs/latest/api/app#appgetpathname

app.getPath takes a single string. path.join concatenates the array of strings together into a properly formatted path.

Though I would actually suggest using this
```suggestion
    app.getPath('home'),
    'github',
    'pulsar'
```
because the default git folder _is_ `github` when installing git (at least on windows). And I would personally discourage users from cloning repos directly into their home folder

2022-12-20 03:04 UTC, CatPerson136 reviewed
ok thank you it is fixed

2022-12-20 03:05 UTC, CatPerson136 commented
Made the changes

2022-12-20 10:06 UTC, CatPerson136 commented on src/main-process/main.js
> +    app.getPath('home','pulsar-edit','pulsar')
Ok will fix

2022-12-24 22:33 UTC, CatPerson136 commented
Is this thread's deal active or should I close it?

2022-12-25 04:36 UTC, mauricioszabo commented
So, while I approve this change, I don't see us using dev mode and the resources path anymore. They also conflict with the idea of bundling packages, and some of the work to use ESM modules also will conflict with the idea of the resources path.

Anyway, we can merge this PR because we're not sure when we will remove the old resources path too 😆

2022-12-25 04:36 UTC, mauricioszabo approved these changes

2022-12-25 04:38 UTC, Spiker985 approved these changes

2022-12-25 04:49 UTC, merged