made cirrus build scripts consistent
pulsar-edit/pulsar pull request #239
Opened 2022-12-16 10:14 UTC by Sertonix

This makes the cirrus build scripts more consistent. It changes the names of the scripts to be consistent and it puts the scripts into a consistend order (`prepair` `install` `build` `build_binary` `test`).

2022-12-19 17:28 UTC, Spiker985 requested changes
The addition of more labels doesn't impact the availability of resources/env vars/etc between instructions, right? It doesn't act like adding an additional job within a GH action?
@mauricioszabo

2022-12-19 17:28 UTC, Spiker985 commented on .cirrus.yml
> +  prepair_script:
```suggestion
  prepare_script:
```

2022-12-19 17:28 UTC, Spiker985 commented on .cirrus.yml
> +  prepair_script:
```suggestion
  prepare_script:
```

2022-12-19 17:28 UTC, Spiker985 commented on .cirrus.yml
> +  prepair_script:
```suggestion
  prepare_script:
```

2022-12-19 17:28 UTC, Spiker985 commented on .cirrus.yml
> +  prepair_script:
```suggestion
  prepare_script:
```

2022-12-19 17:28 UTC, Spiker985 commented on .cirrus.yml
> +  prepair_script:
```suggestion
  prepare_script:
```

2022-12-25 04:32 UTC, mauricioszabo commented
It can impact - it seems that on Silicon Mac it is impacting, so we may need to re-export PATH on the new label

2022-12-25 04:46 UTC, Spiker985 commented
> It can impact - it seems that on Silicon Mac it is impacting, so we may need to re-export PATH on the new label

It looks like the PATH _is_ being re-exported per label for Macs. [L114](https://github.com/pulsar-edit/pulsar/pull/239/files?diff=unified&w=0#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR114), [L117](https://github.com/pulsar-edit/pulsar/pull/239/files?diff=unified&w=0#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR117), [L121](https://github.com/pulsar-edit/pulsar/pull/239/files?diff=unified&w=0#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR121) and [L152](https://github.com/pulsar-edit/pulsar/pull/239/files?diff=unified&w=0#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR152), [L155](https://github.com/pulsar-edit/pulsar/pull/239/files?diff=unified&w=0#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR155), [L159](https://github.com/pulsar-edit/pulsar/pull/239/files?diff=unified&w=0#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bbR159)

Unless you're referring to something else?

2022-12-25 05:01 UTC, Spiker985 approved these changes

2023-02-07 02:34 UTC, DeeDeeG commented on .cirrus.yml
>      - PLAYWRIGHT_JUNIT_OUTPUT_NAME=report.xml npx playwright test --reporter=junit,list
This is per @mauricioszabo's suggestion in a comment above...

```suggestion
  test_script:
    - export PATH="/opt/homebrew/bin:/opt/homebrew/opt/node@16/bin:$PATH"
    - PLAYWRIGHT_JUNIT_OUTPUT_NAME=report.xml npx playwright test --reporter=junit,list
```

Hopefully this fixes the test failure? ("`npx: command not found`")

<details><summary>Full error message:  (click to expand):</summary>

```console
PLAYWRIGHT_JUNIT_OUTPUT_NAME=report.xml npx playwright test --reporter=junit,list
/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/scriptseb9d18a44784045d87f3c67cf22746e9.sh: line 5: npx: command not found
Exit status: 127
```

</details>

2023-03-09 04:51 UTC, DeeDeeG commented
@Sertonix do you mind if I fix the merge conflicts here (and push the merge fix to this branch) and then merge this PR? Or if you want to fix the merge conflicts yourself, I can let you do it.

I would be a second approve for this, since it makes it easier to debug a CI run for any OS even if you've only looked at runs for a different OS before. Also, makes it much easier to keep the different OSes in sync with one-another.

We just have to make it synced with recent .cirrus.yml changes form other PRs.

Thanks for doing this PR in the first place, @Sertonix!

2023-03-09 14:29 UTC, Sertonix commented
@DeeDeeG you can fix the merge conflicts.

2023-03-15 19:36 UTC, DeeDeeG commented
I would want to merge this just after the Regular 1.103 release anticipated later today. So we can shake things up _after_ a Regular release, not just before/in the middle of it. But yeah, I'd like to merge this then.

2023-03-19 23:29 UTC, DeeDeeG approved these changes
Looks good to me. Makes the names and order of the steps consistent for each OS/Arch.

Deletes some commented out steps for Windows and the "Upload Videos Artifacts" step on Windows, which there are currently no videos to upload, since the tests aren't run on Windows...

Approving, will merge soon. Thanks for this! Sorry it took a while to review.

2023-03-19 23:30 UTC, merged