Improved Windows Builds
pulsar-edit/pulsar pull request #279
Opened 2022-12-31 05:02 UTC by confused-Techie

DRAFT PR

Just need the builds for now, will update and ping when ready

2022-12-31 11:09 UTC, confused-Techie commented
@pulsar-edit/core This PR is now ready for review

2023-01-03 02:22 UTC, Spiker985 commented
For the Uninstall Display Name, do we want to shorten in up to Pulsar? Since that's the app name, and Pulsar-Edit is just the org?

2023-01-03 02:24 UTC, confused-Techie commented
> For the Uninstall Display Name, do we want to shorten in up to Pulsar? Since that's the app name, and Pulsar-Edit is just the org?

Yeah we absolutely could. if we think it looks better sure thing. And honestly now that I consider it, the control panel already shows the `Publisher` in the same table when you uninstall, so there's no reason we need to include it in the title.

Also as a side note, the Publisher on Windows does show `Pulsar Community` for some reason

2023-01-03 02:25 UTC, Spiker985 commented
Also, how does allowing the change of install directory affect having a per-user install? Or does it not, because it's being executed as the invoker of the exe anyway?

2023-01-03 02:25 UTC, Spiker985 commented
> Also as a side note, the Publisher on Windows does show `Pulsar Community` for some reason

Bet you it grabs it from the Author field in `package.json`

2023-01-03 02:27 UTC, Spiker985 requested changes

2023-01-03 02:27 UTC, Spiker985 commented on script/electron-builder.js
> +    "uninstallDisplayName": "Pulsar-Edit Pulsar",
```suggestion
    "uninstallDisplayName": "Pulsar",
```

2023-01-03 02:28 UTC, confused-Techie commented
> Also, how does allowing the change of install directory affect having a per-user install? Or does it not, because it's being executed as the invoker of the exe anyway?

IIRC a per user install means it installs into `AppData` since anywhere else it's now global on the system. 

So if we allow the directory to be changed it's now possible to have it be a global install, or per user.

I had hoped that setting `asInvoker` would mean that during installation it would start as the user only, allowing non-admins to still install, and have it only install into `AppData` since a non-admin would need admin access to install globally. 

But, and I'm not sure if this is because I'm an admin on my system) I still got a UAC prompt when running the installer with `asInvoker` set

2023-01-03 02:28 UTC, confused-Techie commented on script/electron-builder.js
> +    "uninstallDisplayName": "Pulsar-Edit Pulsar",
Thanks, saves me from opening the editor lol

2023-01-03 02:28 UTC, confused-Techie commented
> > Also as a side note, the Publisher on Windows does show `Pulsar Community` for some reason
> 
> Bet you it grabs it from the Author field in `package.json`

Should probably fix that huh

2023-01-03 02:31 UTC, Spiker985 commented
> But, and I'm not sure if this is because I'm an admin on my system) I still got a UAC prompt when running the installer with `asInvoker` set

If you told it "no" to the UAC prompt, did it get angry, or carry on it's way? Because if this change fully requires admin, I feel like we'd need to see if we can stop that from happening. I think that requiring admin is a divergence of expectation :thinking:

2023-01-03 02:38 UTC, confused-Techie commented
> > But, and I'm not sure if this is because I'm an admin on my system) I still got a UAC prompt when running the installer with `asInvoker` set
> 
> If you told it "no" to the UAC prompt, did it get angry, or carry on it's way? Because if this change fully requires admin, I feel like we'd need to see if we can stop that from happening. I think that requiring admin is a divergence of expectation 🤔

Looks like without approval on the UAC prompt it does in fact fail. So I do agree it's a change in expectation, but that's essentially what those linked issues are calling for.

I even tried to explain this on one, but they remained steadfast that it's best to install into these other locations.

Possibly should we open up a poll? I didn't realize before it would fail without admin, and honestly I'm not super on board with that idea.

2023-01-03 02:43 UTC, Spiker985 commented
> > > But, and I'm not sure if this is because I'm an admin on my system) I still got a UAC prompt when running the installer with `asInvoker` set
> > 
> > 
> > If you told it "no" to the UAC prompt, did it get angry, or carry on it's way? Because if this change fully requires admin, I feel like we'd need to see if we can stop that from happening. I think that requiring admin is a divergence of expectation thinking
> 
> Looks like without approval on the UAC prompt it does in fact fail. So I do agree it's a change in expectation, but that's essentially what those linked issues are calling for.
> 
> I even tried to explain this on one, but they remained steadfast that it's best to install into these other locations.
> 
> Possibly should we open up a poll? I didn't realize before it would fail without admin, and honestly I'm not super on board with that idea.

Yeah, honestly, if it allowed the choice of "machine-wide" versus "user" install types, and _then_ did the prompt for UAC - I would be okay with it, but since it outright invalidates a non-admin install I would definitely put it to a vote

2023-01-03 10:24 UTC, Sertonix commented on script/electron-builder.js
> +    "perMachine": true,
Removing this line should fix the unintended behaviour.
It essentially forces the installation to be machine wide.

2023-01-03 10:26 UTC, Sertonix commented on script/electron-builder.js
> +    "requestedExecutionLevel": "asInvoker",
Since this is set to the default value it would be cleaner to remove it

2023-01-03 15:03 UTC, mauricioszabo commented
Yeah, I'm also not comfortable with not allowing the user to install without admin powers. If we don't find a way to fix this, I feel we don't need to address the issues - I mean, it's not like Pulsar is _not working_ right?

2023-01-03 15:05 UTC, Sertonix commented
> Yeah, I'm also not comfortable with not allowing the user to install without admin powers. If we don't find a way to fix this, I feel we don't need to address the issues - I mean, it's not like Pulsar is _not working_ right?

Removing `"perMachine": true` as mentioned in my comments should resolve this issue.

2023-01-03 15:39 UTC, mauricioszabo commented
Worth a try, @Sertonix :)

2023-01-03 21:26 UTC, Sertonix commented
@confused-Techie @mauricioszabo The build worked for me.

2023-01-03 23:48 UTC, confused-Techie commented
@Sertonix fantastic work!

This PR now does exactly as I had originally hoped.

This allows users to install Machine wide (into Program Files) or per user (into AppData) and will only require admin permission as needed.

This still doesn't allow the user to install into any directory they would like, but I think is close enough for our needs.

Super glad @Sertonix was able to find the solution here. Since this resolves everyones concerns if it looks good then lets merge, super rad

2023-01-03 23:54 UTC, Spiker985 approved these changes

2023-01-04 00:04 UTC, merged

2023-01-04 00:20 UTC, Neustradamus commented
@confused-Techie: Thanks for your PR!

With your changes, what is the default install place?

2023-01-04 00:25 UTC, confused-Techie commented
> @confused-Techie: Thanks for your PR!
> 
> With your changes, what is the default install place?

The default installation directory is a per-machine install. That is `C:\Program Files\Pulsar` but that does require admin privilege's. If the user does not have admin privilege's then they can install per user, which will be into AppData

2023-01-04 04:31 UTC, Neustradamus commented
@confused-Techie: Can you create test build?

And after, it is needed to create an official new build with this fix!

2023-01-04 04:33 UTC, confused-Techie commented
> @confused-Techie: Can you create test build?
> 
> And after, it is needed to create an official new build with this fix!

Any of the latest Alpha builds should already have this change. They are built automatically from each merged PR. You can download them directly from our [website](https://pulsar-edit.dev/download.html#cirrus-ci-binaries).

But we are hoping to release anther beta when we can, but will likely still be some time.