update `packages/README.md`
pulsar-edit/pulsar pull request #317
Opened 2023-01-07 22:38 UTC by Sertonix

This updates the `packages/README.md`.

2023-01-07 23:04 UTC, confused-Techie requested changes
Overall this looks awesome, and thanks for getting this updated, there was just one mistaken remove that I've pointed out. But otherwise thanks for the contribution!

2023-01-07 23:04 UTC, confused-Techie commented on packages/README.md
> -[snippets]: https://github.com/pulsar-edit/snippets
We will still want to include the `snippets` package link, since we don't have it bundled, and removing this line breaks the link above.

2023-01-07 23:20 UTC, Sertonix commented on packages/README.md
> -[snippets]: https://github.com/pulsar-edit/snippets
fixed it

2023-01-08 01:38 UTC, confused-Techie approved these changes
Thanks for getting to my concern so quickly!

2023-01-08 03:14 UTC, merged