Rebrand to Pulsar in docs
pulsar-edit/pulsar pull request #38
Opened 2022-08-28 23:43 UTC by stechsoft13

### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
Rebrands Atom to Pulsar in documentation. This is made in an effort to rebrand to Pulsar.

### Release Notes
N/A

2022-08-29 01:30 UTC, confused-Techie requested changes
I was going through this PR and found many instances of links like `https://github.com/atom/Pulsar` but we would need those links to be `https://github.com/pulsar-edit/pulsar` instead. 

Also with some links changing `atom.io` links to use `Pulsar` somewhere within, but unfortunately we would need those to point to our new docs site once its up, since as of now those will not resolve anywhere. 

Lastly I noticed you linked to a `Pulsaredit` Twitter account. Which I've commented on directly, but it concerns me to link to a suspended Twitter account within the docs.

2022-08-29 01:30 UTC, confused-Techie commented on docs/Documentation.md
> +Visit [atom.io](https://atom.io) to learn more or visit the [Pulsar forum](https://github.com/atom/Pulsar/discussions).
```suggestion
Visit [atom.io](https://atom.io) to learn more or visit the [Pulsar forum](https://github.com/pulsar-edit/pulsar/discussions).
```

2022-08-29 01:30 UTC, confused-Techie commented on docs/Documentation.md
> +Follow [@PulsarEditor](https://twitter.com/Pulsareditor) on Twitter for important
Is this a Twitter account that you've created? I wasn't aware we had one and this account seems to have already been suspended?

2022-08-29 01:30 UTC, confused-Techie commented on docs/Installation.md
> +Download the latest [Pulsar release](https://github.com/atom/Pulsar/releases/latest).
```suggestion
Download the latest [Pulsar release](https://github.com/pulsar-edit/pulsar/releases/latest).
```

2022-08-29 01:30 UTC, confused-Techie commented on docs/Installation.md
> +Download the latest [Pulsar installer](https://github.com/atom/Pulsar/releases/latest). `PulsarSetup.exe` is 32-bit. For 64-bit systems, download `PulsarSetup-x64.exe`.
```suggestion
Download the latest [Pulsar installer](https://github.com/pulsar-edit/pulsar/releases/latest). `PulsarSetup.exe` is 32-bit. For 64-bit systems, download `PulsarSetup-x64.exe`.
```

And I'm not sure if these names will match up with our eventual binaries, but would imagine they probably will.

2022-08-29 01:30 UTC, confused-Techie commented on docs/Installation.md
> +You can also download `Pulsar-windows.zip` (32-bit) or `Pulsar-x64-windows.zip` (64-bit) from the [releases page](https://github.com/atom/Pulsar/releases/latest).
```suggestion
You can also download `Pulsar-windows.zip` (32-bit) or `Pulsar-x64-windows.zip` (64-bit) from the [releases page](https://github.com/pulsar-edit/pulsar/releases/latest).
```

2022-08-29 01:30 UTC, confused-Techie commented on docs/Installation.md
> +Configure your distribution's package manager to install and update Pulsar by following the [Linux installation instructions](https://flight-manual.atom.io/getting-started/sections/installing-Pulsar/
Unfortunately since we don't have control over the `https://flight-manual.atom.io` domain, this link won't resolve. We will need to wait to change the links within documentation until we have a mirror setup

2022-08-29 01:45 UTC, stechsoft13 commented on docs/Documentation.md
> +Follow [@PulsarEditor](https://twitter.com/Pulsareditor) on Twitter for important
For some reason I did not notice that.

2022-08-29 01:49 UTC, stechsoft13 commented on docs/Installation.md
> +Configure your distribution's package manager to install and update Pulsar by following the [Linux installation instructions](https://flight-manual.atom.io/getting-started/sections/installing-Pulsar/
Maybe we could leave a note.

2022-08-29 01:52 UTC, confused-Techie commented on docs/Documentation.md
> +Follow [@PulsarEditor](https://twitter.com/Pulsareditor) on Twitter for important
Okay rad, yeah we may just want to remove that section, unless we plan to create a Twitter account

2022-08-29 01:53 UTC, confused-Techie commented on docs/Installation.md
> +Configure your distribution's package manager to install and update Pulsar by following the [Linux installation instructions](https://flight-manual.atom.io/getting-started/sections/installing-Pulsar/
We could leave a warning that this links to old docs and leave them as is? So that way at least it gives the user some documentation and gives us a reminder to loop back to it, but that'd work for me

2022-08-29 01:55 UTC, stechsoft13 commented on docs/Installation.md
> +Configure your distribution's package manager to install and update Pulsar by following the [Linux installation instructions](https://flight-manual.atom.io/getting-started/sections/installing-Pulsar/
> We could leave a warning that this links to old docs and leave them as is? So that way at least it gives the user some documentation and gives us a reminder to loop back to it, but that'd work for me

A note seems better since it's not IMPORTANT information.

2022-08-29 01:56 UTC, stechsoft13 commented on docs/Documentation.md
> +Follow [@PulsarEditor](https://twitter.com/Pulsareditor) on Twitter for important
VS Code decided to add a PulsarEditor Twitter to documentation

2022-08-29 02:00 UTC, stechsoft13 commented on docs/Installation.md
> +Configure your distribution's package manager to install and update Pulsar by following the [Linux installation instructions](https://flight-manual.atom.io/getting-started/sections/installing-Pulsar/
installing-Pulsar section:
I unfortunately can't do that since I'm sort of tired to do that, but you can do that on your own, it's easy.

2022-08-29 02:43 UTC, confused-Techie reviewed
This looks a lot better, just added a few things that slipped the cracks. Mostly again with `flight-manual` links, and many of the repo links `atom/Pulsar` that would 404. 

But thanks for the contribution.

2022-08-29 02:43 UTC, confused-Techie commented on docs/rfcs/005-scope-naming.md
> +This is tricky, of course — not only the coordination of PRs across packages, but also the need to apply overrides to all six (is it six? I think it’s six) of the built-in syntax themes. If all built
```suggestion
This is tricky, of course — not only the coordination of PRs across packages, but also the need to apply overrides to all six (is it six? I think it’s six) of the built-in syntax themes. If all built-in themes are going to share an austere philosophy ([and it seems like that’s the plan](https://github.com/atom/atom/pull/18383#issuecomment-435460854)), then perhaps it makes sense for them to start sharing a core set of contextual rules. The only difference between them would be the specific color choices that they make.
```

While wanting to make sure links will actually resolve as `atom/Pulsar` doesn't exist, for something talking about historical changes it may be best to leave as the historical PR. Since that PR won't exist on our fork, if we changed it to `pulsar-edit/pulsar`. Otherwise we could change it instead to the Git Reference on our repo? 

Hard to say but my vote would be for leaving it as the historical PR.

2022-08-29 02:43 UTC, confused-Techie commented on docs/rfcs/005-pretranspile.md
> +When a user installs a package from atom.io, atom.io first checks to see if it has a precompiled tarball in its S3 bucket. If one is found, the artifact's public URL is returned as the `dist` field i
Still with this link it 404's. Either I'd recommend changing it to still just be the original atom docs, or to point to the appropriate file on `puslar-edit/docs`. Unless we want to wait on merging this PR until the GitHub Pages for `docs` is configured.

2022-08-29 02:43 UTC, confused-Techie commented on docs/rfcs/005-pretranspile.md
> +* Standard `npm` tooling like `prepare` scripts will work for apm packages exactly as they work for npm packages. This will remove the need for custom transpiler pipeline modules like [Pulsar-babel6-
```suggestion
* Standard `npm` tooling like `prepare` scripts will work for apm packages exactly as they work for npm packages. This will remove the need for custom transpiler pipeline modules like [atom-babel6-transpiler](https://github.com/pulsar-edit/atom-babel6-transpiler) or [atom-typescript-transpiler](https://github.com/smhxx/atom-ts-transpiler) with their own, independent documentation, configuration and setup.
```

* atom-typescript-transpiler: This is a tool created by a third party, which we cannot change its name, unless we wanted to maintain our own fork of it. But as such we should leave its original name, since otherwise this link 404s.
* atom-babel16-transpiler: We could have this point to our fork of the repo, although its repo name is still under atom. That likely is something we will want to change. But at this time has not happened yet.

2022-08-29 03:00 UTC, stechsoft13 commented
@confused-Techie I don't know if any issues are present now.

2022-08-31 07:56 UTC, confused-Techie requested changes
So I've gone ahead and requested changes.

I apologize if I wasn't clear before, but with pointing out previous issues, was less of heres the one instance, and more this is a recurring issue within the PR. So I've made it more obvious and except the largest document, I've gone ahead and pointed out each instance I was able to identify.

1. Repo links not being correct. The format is `owner/repo` so `pulsar-edit/repo`
2. Links to `atom.io` not resolving due to the replacement of `Pulsar` wherever `atom` was, which again we do not have control over this domain so we cannot change the links of those locations. While you are correct that I can make these changes, I cannot merge a PR that purposefully and knowingly breaks functionality.
3. Lastly There is the question of historical data, which I will highlight more below.

@pulsar-edit/documentation The question of historical data. If there is a document or text that refers to `atom` in a historical way, such as 
* The decision to name `Atom Dev` was decided based on [this]() Twitter poll.
* This new Atom feature was decided in 2010.

And so on, should this be changed? We didn't make those decisions, and the history there is not ours, while we are rebranding, it seems dishonest to rebrand past events as ours.

But please feel free to expand on this conversation.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +- By reading README.md, maybe they will decide to click the link to the Atom Flight Manual and _maybe_ find the [Contributing to Official Pulsar Packages](https://flight-manual.atom.io/hacking-atom/s
```suggestion
- By reading README.md, maybe they will decide to click the link to the Atom Flight Manual and _maybe_ find the [Contributing to Official Pulsar Packages](https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/) page there
```
This link does not resolve as is.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +- They could read the CONTRIBUTING.md file which [has a section](https://github.com/atom/Pulsar/blob/master/CONTRIBUTING.md#Pulsar-and-packages) that explains where to find the repos for core package
```suggestion
- They could read the CONTRIBUTING.md file which [has a section](https://github.com/pulsar-edit/pulsar/blob/master/CONTRIBUTING.md#Pulsar-and-packages) that explains where to find the repos for core packages and how to contribute, but we don't really have a clear pointer to that in our README.md
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +- If they don't happen to find that page, they might use Google to search for "Pulsar tree view" and find the Pulsar/tree-view repo and _maybe_ read the CONTRIBUTING.md file which sends them to Pulsa
```suggestion
- If they don't happen to find that page, they might use Google to search for "Pulsar tree view" and find the pulsar-edit/tree-view repo and _maybe_ read the CONTRIBUTING.md file which sends them to Pulsar's overall contribution documentation
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +1. Fork and clone `Pulsar/Pulsar` and switch to a release branch if necessary
```suggestion
1. Fork and clone `pulsar-edit/pulsar` and switch to a release branch if necessary
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +If we were to move `tree-view` (or any other core Pulsar package) back into `Pulsar/Pulsar`, the development workflow would look more like this:
```suggestion
If we were to move `tree-view` (or any other core Pulsar package) back into `pulsar-edit/pulsar`, the development workflow would look more like this:
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +1. Open a PR on `Pulsar/Pulsar` and wait for CI to pass and a maintainer to review it
```suggestion
1. Open a PR on `pulsar-edit/pulsar` and wait for CI to pass and a maintainer to review it
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +Since packages all have their own repositories, this means that we have to watch 91 different repos for issues and pull requests.  This also means that we have to redirect issues filed on `Pulsar/Pul
```suggestion
Since packages all have their own repositories, this means that we have to watch 91 different repos for issues and pull requests.  This also means that we have to redirect issues filed on `pulsar-edit/pulsar` to the appropriate repository when a user doesn't know where it belongs.  Even more importantly, there's not an easy way to prioritize and track issues across the Pulsar organization without using GitHub Projects.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +The more core packages live in `Pulsar/Pulsar`, the less work Pulsar maintainers have to do overall.
```suggestion
The more core packages live in `pulsar-edit/pulsar`, the less work Pulsar maintainers have to do overall.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +Many of Pulsar's core packages now live in the core `Pulsar/Pulsar` repository.  To the Pulsar user, this change will be imperceptible as these packages still show up in the list of Core Packages in
```suggestion
Many of Pulsar's core packages now live in the core `pulsar-edit/pulsar` repository.  To the Pulsar user, this change will be imperceptible as these packages still show up in the list of Core Packages in the Settings View.  Users can still optionally disable these packages.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +Contributors now clone and build `Pulsar/Pulsar` to work on improvements to core packages.  They will no longer have to use `apm link` in dev mode to test changes they make to packages in the repo's
```suggestion
Contributors now clone and build `pulsar-edit/pulsar` to work on improvements to core packages.  They will no longer have to use `apm link` in dev mode to test changes they make to packages in the repo's `packages` folder.  Core packages that aren't consolidated still have folders under `packages` with README.md files that point to the home repository for that package.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +When a contributor sends a PR to `Pulsar/Pulsar` that only affects files in a folder under `packages`, only the specs for the relevant package folders will be executed using Pulsar's CI scripts.  Thi
```suggestion
When a contributor sends a PR to `pulsar-edit/pulsar` that only affects files in a folder under `packages`, only the specs for the relevant package folders will be executed using Pulsar's CI scripts.  This means that a full Pulsar build will not be required when no Pulsar Core code is changed in a PR.  Package specs are also now run against all 3 OSes on Pulsar `master` and release builds.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +Pulsar maintainers no longer have to publish new versions to consolidated core packages and then edit `package.json` to bump the package version in a particular Pulsar release branch (Stable, Beta, o
```suggestion
Pulsar maintainers no longer have to publish new versions to consolidated core packages and then edit `package.json` to bump the package version in a particular Pulsar release branch (Stable, Beta, or `master`).  When a PR against a consolidated core package in `pulsar-edit/pulsar` is merged, no version number change is required and the changes will immediately be a part of the next release from that branch.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +One possible drawback of this approach is that there might be some initial confusion where core Pulsar packages live, especially if some are consolidated into `Pulsar/Pulsar` and others still live in
```suggestion
One possible drawback of this approach is that there might be some initial confusion where core Pulsar packages live, especially if some are consolidated into `pulsar-edit/pulsar` and others still live in their own repositories.  We will manage this confusion by doing the following:
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +Also, contributors will now have to fork, clone, and build `Pulsar/Pulsar` to contribute to core packages where they would previously just need to clone the package repository.  This might put added
```suggestion
Also, contributors will now have to fork, clone, and build `pulsar-edit/pulsar` to contribute to core packages where they would previously just need to clone the package repository.  This might put added burden on them such as installing necessary build dependencies on their machine that they wouldn't otherwise need.  It is very likely we could simplify this process for them, though.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +The Motivation section explains most of the rationale, so this section will focus on the process of consolidating packages back into `Pulsar/Pulsar`. The set of packages we've chosen to consolidate w
```suggestion
The Motivation section explains most of the rationale, so this section will focus on the process of consolidating packages back into `pulsar-edit/pulsar`. The set of packages we've chosen to consolidate were evaluated based on a few factors:
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +| **[Pulsar-dark-syntax]** | 5 | 0 | 0 | 12/6/17 |
```suggestion
| **[atom-dark-syntax]** | 5 | 0 | 0 | 12/6/17 |
```
Repo has not been renamed.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +| **[Pulsar-dark-ui]** | 1 | 2 | 0 | 2/13/18 |
```suggestion
| **[atom-dark-ui]** | 1 | 2 | 0 | 2/13/18 |
```
Repo has not been renamed.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +| **[Pulsar-light-syntax]** | 1 | 0 | 0 | 10/17/16 |
```suggestion
| **[atom-light-syntax]** | 1 | 0 | 0 | 10/17/16 |
```
Repo has not been renamed.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +| **[Pulsar-light-ui]** | 1 | 0 | 0 | 2/13/18 |
```suggestion
| **[atom-light-ui]** | 1 | 0 | 0 | 2/13/18 |
```
Repo has not been renamed.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +- **[autocomplete-Pulsar-api]**
```suggestion
- **[autocomplete-atom-api]**
```
Repo has not been renamed.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +To consolidate a single core package repository back into `Pulsar/Pulsar`, the following steps will be taken:
```suggestion
To consolidate a single core package repository back into `pulsar-edit/pulsar`, the following steps will be taken:
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +1. A PR will be sent to `Pulsar/Pulsar` to verify that CI passes with the introduction of the consolidated package
```suggestion
1. A PR will be sent to `pulsar-edit/pulsar` to verify that CI passes with the introduction of the consolidated package
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +1. The package's original repository will have all of its existing issues moved over to `Pulsar/Pulsar` using a bulk issue mover tool, assigning a label to those issues relative to the package name,
```suggestion
1. The package's original repository will have all of its existing issues moved over to `pulsar-edit/pulsar` using a bulk issue mover tool, assigning a label to those issues relative to the package name, like `packages/tree-view`
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +1. The package's original repository will have its README.md updated to point contributors to the code's new home in `Pulsar/Pulsar`
```suggestion
1. The package's original repository will have its README.md updated to point contributors to the code's new home in `pulsar-edit/pulsar`
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +- Is there a good reason to not move the `language-*` packages into `Pulsar/Pulsar`?
```suggestion
- Is there a good reason to not move the `language-*` packages into `pulsar-edit/pulsar`?
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +  One concern here is that there exist projects which depend directly on these repositories for the TextMate syntax grammars they contain.  Moving the code into `Pulsar/Pulsar` would require that we
```suggestion
  One concern here is that there exist projects which depend directly on these repositories for the TextMate syntax grammars they contain.  Moving the code into `pulsar-edit/pulsar` would require that we notify the consumers of the grammars so that they can redirect their requests to the `pulsar-edit/pulsar` repo.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +- What are the criteria we might use to eventually decide to move larger packages like `tree-view`, `settings-view`, and `find-and-replace` back into `Pulsar/Pulsar`?
```suggestion
- What are the criteria we might use to eventually decide to move larger packages like `tree-view`, `settings-view`, and `find-and-replace` back into `pulsar-edit/pulsar`?
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +[Pulsar-dark-syntax]: https://github.com/atom/Pulsar-dark-syntax
```suggestion
[Pulsar-dark-syntax]: https://github.com/pulsar-edit/atom-dark-syntax
```
This link does not resolve.

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +[Pulsar-dark-ui]: https://github.com/atom/Pulsar-dark-ui
```suggestion
[atom-dark-ui]: https://github.com/pulsar-edit/atom-dark-ui
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +[Pulsar-light-syntax]: https://github.com/atom/Pulsar-light-syntax
```suggestion
[atom-light-syntax]: https://github.com/pulsar-edit/atom-light-syntax
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +[Pulsar-light-ui]: https://github.com/atom/Pulsar-light-ui
```suggestion
[atom-light-ui]: https://github.com/pulsar-edit/atom-light-ui
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/003-consolidate-core-packages.md
> +[autocomplete-Pulsar-api]: https://github.com/atom/autocomplete-Pulsar-api
```suggestion
[autocomplete-atom-api]: https://github.com/pulsar-edit/autocomplete-atom-api
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/rfcs/001-updatable-bundled-packages.md
> +Despite all this, if the user *does* manually install an update to a bundled package using `apm`, it will be loaded into the editor and updated dutifully as new releases occur.  The only new function
Do we know for a fact that this will be the output directory?

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +| [Pulsar](https://github.com/atom/Pulsar) | [![Build status](https://github.visualstudio.com/Pulsar/_apis/build/status/Pulsar%20Production%20Branches?branch=master)](https://github.visualstudio.com/
```suggestion
| [Pulsar](https://github.com/pulsar-edit/pulsar) | [![Build status](https://github.visualstudio.com/Pulsar/_apis/build/status/Pulsar%20Production%20Branches?branch=master)](https://github.visualstudio.com/Pulsar/_build/latest?definitionId=32&branch=master) | | | [![Dependency Status](https://david-dm.org/Pulsar/Pulsar.svg)](https://david-dm.org/Pulsar/Pulsar) |
```

As for these visual studio links they do not resolve

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> See <https://github.com/atom/Pulsar/blob/master/packages/README.md> for details.
```suggestion
> See <https://github.com/pulsar-edit/pulsar/blob/master/packages/README.md> for details.
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [about](https://github.com/atom/Pulsar/tree/master/packages/about)
```suggestion
> - [about](https://github.com/pulsar-edit/oulsar/tree/master/packages/about)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [autoflow](https://github.com/atom/Pulsar/tree/master/packages/autoflow)
```suggestion
> - [autoflow](https://github.com/pulsar-edit/pulsar/tree/master/packages/autoflow)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [deprecation-cop](https://github.com/atom/Pulsar/tree/master/packages/deprecation-cop)
```suggestion
> - [deprecation-cop](https://github.com/pulsar-edit/pulsar/tree/master/packages/deprecation-cop)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [dev-live-reload](https://github.com/atom/Pulsar/tree/master/packages/dev-live-reload)
```suggestion
> - [dev-live-reload](https://github.com/pulsar-edit/pulsar/tree/master/packages/dev-live-reload)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [exception-reporting](https://github.com/atom/Pulsar/tree/master/packages/exception-reporting)
```suggestion
> - [exception-reporting](https://github.com/pulsar-edit/pulsar/tree/master/packages/exception-reporting)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [git-diff](https://github.com/atom/Pulsar/tree/master/packages/git-diff)
```suggestion
> - [git-diff](https://github.com/pulsar-edit/pulsar/tree/master/packages/git-diff)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +| [Ruby on Rails](https://github.com/atom/Pulsar/tree/master/packages/ruby-on-rails) | |
```suggestion
| [Ruby on Rails](https://github.com/pulsar-edit/pulsar/tree/master/packages/ruby-on-rails) | |
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +| [PulsarDoc](https://github.com/atom/Pulsardoc) | [![build](https://github.com/atom/Pulsardoc/workflows/CI/badge.svg)](https://github.com/atom/Pulsardoc/actions) | [![Dependency Status](https://davi
```suggestion
| [PulsarDoc](https://github.com/pulsar-edit/atomdoc) | [![build](https://github.com/atom/Pulsardoc/workflows/CI/badge.svg)](https://github.com/atom/Pulsardoc/actions) | [![Dependency Status](https://david-dm.org/Pulsar/Pulsardoc.svg)](https://david-dm.org/Pulsar/Pulsardoc)
```

The rest of these links do not resolve

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [go-to-line](https://github.com/atom/Pulsar/tree/master/packages/go-to-line)
```suggestion
> - [go-to-line](https://github.com/pulsar-edit/pulsar/tree/master/packages/go-to-line)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [grammar-selector](https://github.com/atom/Pulsar/tree/master/packages/grammar-selector)
```suggestion
> - [grammar-selector](https://github.com/pulsar-edit/pulsar/tree/master/packages/grammar-selector)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [line-ending-selector](https://github.com/atom/Pulsar/tree/master/packages/line-ending-selector)
```suggestion
> - [line-ending-selector](https://github.com/pulsar-edit/pulsar/tree/master/packages/line-ending-selector)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [link](https://github.com/atom/Pulsar/tree/master/packages/link)
```suggestion
> - [link](https://github.com/pulsar-edit/pulsar/tree/master/packages/link)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [ruby-on-rails](https://github.com/atom/Pulsar/tree/master/packages/ruby-on-rails)
```suggestion
> - [ruby-on-rails](https://github.com/pulsar-edit/pulsar/tree/master/packages/ruby-on-rails)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [update-package-dependencies](https://github.com/atom/Pulsar/tree/master/packages/update-package-dependencies)
```suggestion
> - [update-package-dependencies](https://github.com/pulsar-edit/pulsar/tree/master/packages/update-package-dependencies)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +> - [welcome](https://github.com/atom/Pulsar/tree/master/packages/welcome)
```suggestion
> - [welcome](https://github.com/pulsar-edit/pulsar/tree/master/packages/welcome)
```

2022-08-31 07:56 UTC, confused-Techie commented on docs/build-instructions/build-status.md
> +| [About](https://github.com/atom/Pulsar/tree/master/packages/about) |  | [![Dependency Status](https://david-dm.org/Pulsar/about.svg)](https://david-dm.org/Pulsar/about) |
The below section here is filled with links that do not resolve. They will need to be modified to:

1. Have the repo be correct
2. Have the build status reverted to the original linkage.

2022-09-12 03:02 UTC, softcode589 commented
Too much trouble here, anyone can recreate this.

2022-09-12 03:02 UTC, closed without merging