Add `pulsar-updater` as a core bundled Package
pulsar-edit/pulsar pull request #656
Opened 2023-07-26 04:29 UTC by confused-Techie

As most of us are well aware of the conversation of Pulsar being able to auto-update is one that we have seen many times. And while many of us want to support this feature, there are it's obvious issues:

* Electron auto-updates really mean using Squirrel to Auto-update
* Squirrel does not work on Linux at all
* Squirrel requires have the application signed
* Getting the application signed means paying 3rd party companies very large amounts of money for signing on Windows
* Some core developers do not feel we should pay Microsoft for simply publishing a package that's used on their Operating System

With that said, I've constantly been a fan of the alternative. **No** auto-updates. Many many applications don't auto-update, and instead will alert the user of a new update, help them download the installation file, and leave them alone from there. Leaving the user to manage the install process. Personally, I love this method, and think we can easily adopt it here.

For about a couple months I've been working on my own package `pulsar-updater` which does exactly this. This package is intended to be able to alert the user of a new version being available, and help them get that versions binary and nothing more.

The generally workflow of this package looks like this:

1. The package starts, or a user runs `pulsar-updater:check-for-updates` and the update check begins
2. The GitHub API is used to determine if the version available on GitHub is newer than the one installed
3. If a newer version is available then the package will attempt to determine how Pulsar is currently installed
4. The README.md goes into greater detail on what installation methods are supported
5. But if it determines Pulsar has been installed via various package managers, then the user will either be given the commands needed to update the package in the terminal, or otherwise will advise them to use such and such service to update Pulsar.
6. Otherwise, if the installation is determined to be 'manual' then they user will be provided a link that opens up the version on GitHub, so the user can download the right binary.

Even though this package does use a notification, I feel it's the least invasive way we can do this. The notification is easy to dismiss, or even dismiss until next launch if preferred. Additionally, this method requires zero change to our server hosting costs, in the cloud services, how we release binaries, or messing around with squirrel and certificates. This is the simplest possibly way I can see of us providing a near auto-update experience, while still leaving the user in total control.

What I'd really like to see happen with this, is if this package is accepted into core, then we go ahead and begin to mothball all other existing auto-update code, which can hopefully greatly simplify the startup sequence, and remove dependencies. The only big change I think may be worth talking about here, is having a global entry for the configuration of this package to check for updates on launch, and this package respects that global option rather than it's own, to ensure the setting is easy to find.

Please feel more than free to provide feedback of any kind, since especially a change like this is one we have to ensure is reviewed in some way prior to merging. 

### An example image

![image](https://github.com/pulsar-edit/pulsar/assets/26921489/c266b802-bd40-44b3-b971-0f0fc0c344e4)

2023-07-26 06:06 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +            },
Am I right in assuming that **Dismiss** means “dismiss for this window only,” but **Dismiss until next launch** means “dismiss until the user quits and relaunches?”

If so, I'd like to suggest something else:

* **Dismiss until next version**: This would keep checking for new versions whenever a window is opened or reloaded, but wouldn't remind someone about a new version unless it's actually a newer version than it was the last time they clicked this button.
* **Dismiss until next launch**: Whether or not a newer version came out in the interim, this would suppress all version reminders until the next time Pulsar was launched from scratch.

I'd want to get rid of the simple **DIsmiss** altogether because it suggests that if I relaunch Pulsar, and it restores each of the N windows I had open in my last session, I'd have to dismiss N notifications.

2023-07-26 07:02 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +            },
Fantastic suggestion! Technically dismiss does dismiss that version, but only until the cache would time out. So you are right that it's important to ensure it dismisses this version totally, and make the language a lot clearer.

I'll get that added, thanks for the feedback

2023-07-28 02:49 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +            },
@savetheclocktower I've now added the changes necessary to dismiss a specific version rather than the ambiguous "Dismiss"

2023-07-28 03:23 UTC, savetheclocktower commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
Can you mock `checkForUpdates` or something within `superagent`, then check that it was called?

2023-07-28 03:25 UTC, savetheclocktower commented on packages/pulsar-updater/src/find-install-method.js
> +        string: "Home Brew Installation",
```suggestion
        string: "Homebrew Installation",
```

2023-07-28 03:29 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +    );
```suggestion
    this.disposables.add(
      atom.commands.add("atom-workspace", {
        "pulsar-updater:check-for-update": () => {
          this.checkForUpdates();
        },
        "pulsar-updater:clear-cache": () => {
          this.cache.empty("last-update-check");
          this.cache.empty(`installMethod.${atom.getVersion()}`);
        },
      })
    );
```

Haven't tested it, but this ought to work.

2023-07-28 03:34 UTC, savetheclocktower commented on packages/pulsar-updater/src/find-install-channel.js
> +  }
```suggestion
  return debGetCheck.stdout.includes("pulsar");
```

2023-07-28 03:35 UTC, savetheclocktower commented on packages/pulsar-updater/src/find-install-channel.js
> +  }
```suggestion
  return process.env.FLATPAK_ID === "dev.pulsar_edit.Pulsar";
```

2023-07-28 03:39 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +          "Declining update suggestion since Pulsar is in Spec Mode.";
Should we just refrain from showing the notification in these modes, rather than add this text to the notification? Seems odd.

2023-07-28 03:47 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +    };
```suggestion
    const openWebGitHub = (e) => {
      e.preventDefault();
      shell ??= shell || require("electron").shell;
      let latestVersion = this.cache.getCacheItem("last-update-check")?.latestVersion;
      let tagSegment = latestVersion ? `tag/${latestVersion}` : "";
      shell.openExternal(`https://github.com/pulsar-edit/pulsar/releases/${tagSegment}`);
    };
```

Haven't tested this snippet, but I had the instinct to try to guard against a failed cache lookup, even if it's implausible. If the lookup fails, we'll just bring the user to `https://github.com/pulsar-edit/pulsar/releases/`, which will have the latest release at the top anyway.

2023-07-28 03:55 UTC, savetheclocktower commented on packages/pulsar-updater/README.md
> +* `pulsar-updater:clear-cache`: If needed for whatever reason, this command will clear this package's cache, ensuring information is as up to date as possible.
```suggestion
* `pulsar-updater:check-for-update`: Performs an update check and shows a notification if a newer version of Pulsar is available.
* `pulsar-updater:clear-cache`: Clears the package's cache and forgets any requests to suppress update checking.
```

2023-07-28 03:55 UTC, savetheclocktower commented on packages/pulsar-updater/README.md
> +* Download from GitHub: This option is only shown if the installation method was determined to be manually. And clicking it will open the GitHub page containing the specific version to update to.
These options should be updated. I'd rewrite them myself but I am pretty sleepy.

2023-07-28 03:57 UTC, savetheclocktower commented on packages/pulsar-updater/README.md
> +It's important to remember at this stage, that this update system is in no way integrated with the rest of Pulsar at all. The toggles within Pulsar to automatically update are ignored, as no updates
```suggestion
It's important to remember that this update system is in no way integrated with the rest of Pulsar. The toggles within Pulsar to update automatically are ignored. The About view will still be unable to alert of new versions, nor track progress on installation. Those systems should eventually be removed, or mothballed, in favour of this.
```

2023-07-28 04:00 UTC, confused-Techie commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
I'm testing something like this currently, thanks for the suggestion. The difficult part is that since the `main.js` returns a new instance of the class, we can't ever really spy on that method. But I'm testing this possibility by using superagent. If that fails, we could move the update check out of the class entirely, then spy on that.

2023-07-28 04:02 UTC, savetheclocktower commented
Should've done a proper review, but just kept adding single comments. Apologies.

I can look at this more tomorrow and perhaps give it actual approval.

2023-07-28 04:03 UTC, confused-Techie commented
> Should've done a proper review, but just kept adding single comments. Apologies.
> 
> I can look at this more tomorrow and perhaps give it actual approval.

No apologies needed. I really appreciate you giving this one a look. And hope to have all your fantastic suggestions in by tonight if possible. Then could be awesome if this is ready to go! But we will see, appreciate your time, thanks

2023-07-28 04:13 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +    };
Very smart move, yeah in it's current implementation the cache should always be set prior to this point, but in case theres change in the package later this is a really good idea.

2023-07-28 04:23 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +          "Declining update suggestion since Pulsar is in Spec Mode.";
I initially avoided it, since this function has no easy way to abort the text, but I've added this in, to no longer prompt in safe or spec mode. But the dev mode still does show a notification, if only because I find the text endearing lol

2023-07-28 04:26 UTC, confused-Techie commented on packages/pulsar-updater/README.md
> +* Download from GitHub: This option is only shown if the installation method was determined to be manually. And clicking it will open the GitHub page containing the specific version to update to.
Updated as requested

2023-07-28 04:50 UTC, confused-Techie commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
Yeah on this one I'd be more than happy for any code suggestions. I've tried mocking the calls to `superagent`, `cache`, and `atom.getPackage("pulsar-updater").mainModule.prototype.checkForUpdates` but none of those spys ever seem to be called. Although to be fair, I've never been the most familiar with our testing library, so I may just be missing something.

2023-07-28 05:54 UTC, savetheclocktower commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
After activating the package, you should be able to grab the main module and mock `checkForUpdates` directly without going through the prototype.

2023-07-28 05:58 UTC, confused-Techie commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
I appreciate the suggestion and went ahead and tried it with the following snippet:

```javascript
let pack = atom.packages.getActivePackage("pulsar-updater");

spyOn(pack.mainModule, "checkForUpdates");

atom.commands.dispatch("application", "pulsar-updater:check-for-updates");

expect(pack.mainModule.checkForUpdates).toHaveBeenCalled();
```

I also tried:

```javascript
let pack = atom.packages.getActivePackage("pulsar-updater");

let spy = spyOn(pack.mainModule, "checkForUpdates");

atom.commands.dispatch("application", "pulsar-updater:check-for-updates");

expect(spy).toHaveBeenCalled();
```

But unfortunately this is the only output I get from either test:

```bash
......................F

PulsarUpdater
  when pulsar-updater:check-for-updates is triggered
    it triggers an update check
      Expected spy checkForUpdates to have been called.
        at jasmine.Spec.<anonymous> (D:\Personal Documents\GitHub Repositories\pulsar-edit\pulsar-updater\spec\pulsar-updater-spec.js:26:19)


Finished in 0.477 seconds
23 tests, 25 assertions, 1 failure, 0 skipped
```

2023-07-28 05:59 UTC, savetheclocktower commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
I'll give it a try tomorrow.

2023-07-28 06:00 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +          detail: notificationDetailText,
You might want `description` instead of `detail` here, because this is a prose message rather than a stacktrace. `description` will give you a normal proportional font and the ability to use Markdown.

2023-07-28 06:00 UTC, confused-Techie commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
That'd be awesome if you're able to find what I'm missing here. I'll see if there's anything else I haven't tried yet to get it to work

2023-07-28 06:02 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +          detail: notificationDetailText,
Good catch!

2023-07-30 05:25 UTC, savetheclocktower commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
A few things going on here:

* You were dispaching a command called `pulsar-updater:check-for-updates` instead of `pulsar-updater:check-for-update`
* It was calling through to `superagent` right away on activation until I set `pulsar-updater.checkForUpdatesOnLaunch` to `false`
* `atom.commands.dispatch` needs an actual DOM node as a first argument, not a string

2023-07-30 05:26 UTC, savetheclocktower commented on packages/pulsar-updater/spec/pulsar-updater-spec.js
> +      // TODO find how to check for this
I’d add it as a suggestion, but this conversation in the middle is making it impossible to select the whole thing, so

```js
describe('PulsarUpdater', () => {
  let pack, workspaceElement;
  beforeEach(async () => {
    atom.config.set("pulsar-updater.checkForUpdatesOnLaunch", false);
    workspaceElement = atom.views.getView(atom.workspace);
    pack = await atom.packages.activatePackage('pulsar-updater');
    spyOn(pack.mainModule, 'checkForUpdates');
  });

  afterEach(async () => {
    await atom.packages.deactivatePackage('pulsar-updater');
  });

  describe('when pulsar-updater:check-for-updates is triggered', () => {
    it('triggers an update check', () => {
      atom.commands.dispatch(workspaceElement, 'pulsar-updater:check-for-update');
      expect(pack.mainModule.checkForUpdates).toHaveBeenCalled();
    });
  });
});
```

2023-07-30 05:32 UTC, savetheclocktower commented
I'd love to see a few more tests in `pulsar-updater-spec.js`. Can you write tests that mock various responses from `superagent` (version matches yours, version exceeds yours, each with a cache entry present and each without) and verify that the right things happen?

2023-07-30 05:47 UTC, confused-Techie commented
> I'd love to see a few more tests in `pulsar-updater-spec.js`. Can you write tests that mock various responses from `superagent` (version matches yours, version exceeds yours, each with a cache entry present and each without) and verify that the right things happen?

This is a great idea, to make sure we can know what will happen in every possible scenario. But since I was having trouble mocking the call in my previous testing attempts I may go ahead and move that to be it's own static method of the class, which if memory serves means I'll be able to mock it more easily. But thanks a ton for the feedback!

2023-07-30 08:47 UTC, savetheclocktower commented
Here's roughly what I did:

* Split major decision points into their own methods; we can spy on those methods and assert that they were called rather than directly testing whether a notification was sent
* Added a few specs to test both the notification behavior and the caching behavior
* Left a few comments for things that could be enhanced in the future (but which shouldn't hold up this PR)

Some notes:
* I think that it'd be a good idea if the “Check for Update“ command always checked for a new version, even if the user had previously told us not to notify them — because they've manually invoked the command, so we can assume they want to know. Likewise, if they're already on the newest version, but invoke the “Check for Update” command, we should show a “you're already on the latest version” notification rather than be silent. This isn't something that needs to hold up this PR, but I'd be interested in adding this functionality pretty soon.
* I'm not clear on whether “Dismiss until next launch” is doing the thing that it says on the tin. When the user clicks that button, it seems that we're clearing the cache, making it so that the user will get notified of the new version again at the very next opportunity. My goal with that request is that I should only have to see the “there's a new version” notification a maximum of once per session per new version. If Pulsar is already open and I launch a new project, I shouldn't have to see that notification again, especially if I've recently clicked “Dismiss until next launch.”

The tests I wrote aren't comprehensive, and specifically don't address “Dismiss until next launch” because of my aforementioned confusion, but this should be enough to get you started.

2023-07-30 09:42 UTC, confused-Techie commented
@savetheclocktower This looks fantastic! I really appreciate your help here!

So with this improvements, you are right about the "Dismiss until next launch". Basically it assumes that when an update is checked for it's because of Pulsar being launched. So it clears the cache, and the next update check will go through, which you are correct in that if you launch a second instance of Pulsar you will then see the notification.

We could look into if there's an event that's only fired on Pulsar's first launch, or look for a similar event and check for any other instances. It's very likely possible, if a little bit more complex.

But I appreciate you touching on one of my biggest gripes with the current implementation, that even invoking the command can result in zero output. So I'll work on that then prior to merging this, but yeah I'm not aware of a totally simple implementation for a true "...until next launch" solution

2023-07-30 17:55 UTC, savetheclocktower commented
`sessionStorage` _might_ do what you want. It's much like `localStorage`, but goes away after a session is over, which (if we're lucky) might map perfectly to what we want to accomplish here.

2023-07-30 17:58 UTC, savetheclocktower commented
Never mind — just checked it. Each window has its own `sessionStorage`, unlike `localStorage`.

2023-07-30 18:27 UTC, savetheclocktower commented
My updated feature request is this: in the scenario where multiple windows show the notification at the same time, we should make it so that dismissing one of them ends up dismissing all of them somehow.

Again, this is just brainstorming and not a demand for this particular PR.

2023-07-30 18:28 UTC, savetheclocktower commented
My other suggestion is that we ship this in 1.108, but with the option _disabled_ by default so that we can test it out. Core team can enable the setting, and if the update to 1.109 goes well, then maybe we can do a 1.109.1 that switches the default to `true` for everyone.

2023-07-30 20:55 UTC, confused-Techie commented
@savetheclocktower I do like your ideas here on trying to sync up the behavior of each notification. And we can certainly investigate if this is possible. But now that I look at the startup sequence of Pulsar, I'm not actually sure that each package is able to access other instances of Pulsar, so may prove difficult. But we can certainly look into it.

Otherwise, if it makes you feel any better about shipping it in 1.108.0 as enabled, I was able to ensure it worked in it's current implementation prior to the 1.107.1 update, but may be best to ship disabled if we prefer to make sure it works on all platforms. As long as we know for a fact changing the default would also change the setting for users, which I believe it should.

But I'll get to that last change we wanted today, of not having silence when invoked.

2023-08-02 00:12 UTC, confused-Techie commented
@savetheclocktower 
I've push an update that will ensure that if the user has manually triggered a check, then they will be notified either of:

* The version not needing to be updated
* A version they previous ignored

From here we can still change the default if you'd like, but I'd be comfortable shipping with this default. Curious to hear your thoughts

2023-08-02 00:58 UTC, savetheclocktower commented
Oh, one other thing I thought of: do we handle the case of the user not being connected to the internet? Just want to make sure it doesn't show the user a notification when it fails.

2023-08-02 01:20 UTC, confused-Techie commented
> I think it's fine if an error is thrown in the console as long as it doesn't leak out to the user as a notification or anything else that's visible, because they'll surely already know that they're not connected to the internet, and won't appreciate a complaint from us.

Very fair point. Yeah It shouldn't log any errors as a notification, unless the entire package crashes, which shouldn't be the case. So we should be good there

2023-08-02 03:58 UTC, savetheclocktower commented
> From here we can still change the default if you'd like, but I'd be comfortable shipping with this default. Curious to hear your thoughts

I tend to be paranoid, but I won't insist on a slow rollout if I'm the only one who feels that way. If we ship with it on, we should all be using it ahead of 1.108, and if anything goes sideways, we should be prepared to push out a _very_ quick 1.108.1.

2023-08-02 04:00 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +          this.checkForUpdates();
Can we do something like

```suggestion
          this.checkForUpdates({ manual: true });
```

instead? Then we don't have to worry about resetting `manuallyTriggeredCheck` later on.

2023-08-02 04:07 UTC, savetheclocktower requested changes
I should've just made my original suggestion and then trusted you to make the associated changes, but I got carried away.

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +  async checkForUpdates() {
```suggestion
  async checkForUpdates({ manual = false } = {}) {
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +      }
```suggestion
      if (manual) {
        await this.notifyAboutUpdate(latestVersion);
      }
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +      await this.notifyAboutCurrent(latestVersion);
```suggestion
      // This can be a no-op or something that generates an actual notification
      // based on how the update check was invoked.
      await this.notifyAboutCurrent(latestVersion, manual);
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +  }
```suggestion
  notifyAboutCurrent(latestVersion, manual) {
    if (!manual) return;
    atom.notifications.addInfo(
      "Pulsar is already up to date.",
      { dismissable: true }
    );
  }
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +      this.manuallyTriggeredCheck = false;
```suggestion
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +    this.manuallyTriggeredCheck = false;
```suggestion
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +    this.manuallyTriggeredCheck = false;
```suggestion
```

2023-08-02 04:07 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +          this.manuallyTriggeredCheck = true;
```suggestion
```

2023-08-02 04:09 UTC, savetheclocktower commented
Also, now that we've got code paths that spawn notifications no matter which mode we're in, you should be able to spy on `atom.notifications.*` methods to ensure they get called for those code paths.

2023-08-02 04:14 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +  async checkForUpdates() {
While I haven't tested couldn't this just be `async checkForupdates(manual = false)` to make it simpler?

2023-08-02 04:51 UTC, savetheclocktower commented on packages/pulsar-updater/src/main.js
> +  async checkForUpdates() {
It certainly could. I have an allergy to positional boolean arguments, but I probably go too far in the other direction sometimes.

2023-08-02 14:47 UTC, confused-Techie commented on packages/pulsar-updater/src/main.js
> +  async checkForUpdates() {
@savetheclocktower Ya know that's a totally fair point. If you'd rather provide an object to then have named arguments rather than mystery booleans, I can get on board with that.

Thanks a ton for the suggestions I'll add them in

2023-08-05 23:02 UTC, confused-Techie commented
@savetheclocktower Do you think we should testing the spawning of notifications as well? Or should our current test set be sufficient?

2023-08-09 23:57 UTC, savetheclocktower approved these changes
👍

2023-08-10 00:19 UTC, confused-Techie commented
@savetheclocktower Thanks for approval! I'll go ahead and merge this one!

2023-08-10 00:19 UTC, merged