[core & settings-view] Avoid network requests for bundled packages
pulsar-edit/pulsar pull request #711
Opened 2023-09-08 02:56 UTC by confused-Techie

In this PR I've made three changes:

* Added `atom.branding.urlCoreRepo` to equal the value of our `package.json`s `repository.url`
* Don't hit the GitHub API for getting our org picture for `settings-view`, instead just load the `pulsar.png` that comes with every installation
* Don't hit the backend API for getting download counts and star counts, instead just skip loading them totally

These changes are all focused on reducing the amount of times we hit the backend unnecessarily. As nobody is really installing our bundled packages, it doesn't make much sense to show download counts or stargazer counts for them. Additionally, loading a locally stored image reduces the amount of network requests needed for every user.

2023-09-10 02:14 UTC, DeeDeeG requested changes

2023-09-10 02:14 UTC, DeeDeeG commented on src/atom-environment.js
> +      urlCoreRepo: packagejson.repository.url
Tried to see if this PR was working as intended, but it didn't seem to be skipping the requests, even though the code seemed good. The avatar it's using looks different from `resources/pulsar.png`, too.

So, seeing it not quite working as intended, I looked at Pulsar's package.json, and the `repository.url` value is: `https://github.com/pulsar-edit/pulsar.git`. (Note the  **`.git`** at the end.)

With that `.git` at the end, I think that's why it's not matching the packages' `repository` value, which don't have the `.git` at the end.

So, I wonder if we want to update that `repository.url` in Pulsar editor's main package.json to drop the `.git` at the end of it? Or else hard-code `https://github.com/pulsar-edit/pulsar` as the value of `branding.urlCoreRepo`?

2023-09-10 02:23 UTC, DeeDeeG commented on src/atom-environment.js
> +      urlCoreRepo: packagejson.repository.url
I guess we could alternatively check that `atom.branding.urlCoreRepo.includes(this.pack.repository)` ???

But I think doing this, and leaving the `.git` at the end of `branding.urlCoreRepo` would make it not that useful to most people or for most usage scenarios, since I don't think we or anybody typically wants the `.git` at the end...

2023-09-11 03:33 UTC, confused-Techie commented on src/atom-environment.js
> +      urlCoreRepo: packagejson.repository.url
Great find on this one. Totally missed that. But I agree probably just removing the `.git` at the end of the repo makes total sense. And I don't see it being to problematic of a change.

I'll get that added into this PR as soon as I can

2023-09-11 14:59 UTC, confused-Techie commented on src/atom-environment.js
> +      urlCoreRepo: packagejson.repository.url
@DeeDeeG I've added the changes recommended. Where I've removed the `.git` at the end. So from here after some testing lets see if this is good to go

2023-09-15 05:30 UTC, DeeDeeG reviewed
As a general comment on the idea of using `resources/pulsar.png`, it does change the aesthetics a bit. Since our GitHub org icon and the `resources/pulsar.png` app icon are a bit different.

Screenshots:

Before:

![Package card in the package settings page, showing a purple Pulsar icon with no circle around it and no background](https://github.com/pulsar-edit/pulsar/assets/20157115/8393f984-25ca-46bd-b740-37aac226caaa)

After:

![Package card in the package settings page, showing a white Pulsar icon on a purple circle background](https://github.com/pulsar-edit/pulsar/assets/20157115/4586fbb2-ea4d-47b0-b155-475851716351)

I kinda like the org icon? Maybe we can provide that for use here, such as at file path `resources/pulsar-edit-org.png`?


(This is a moot point if the path resolution isn't fixed in a cross-platform manner, see specific code comment below for addressing that issue, might be a macOS-specific issue, IDK, but I provided a fix with code suggestions.)

2023-09-15 05:30 UTC, DeeDeeG commented on packages/settings-view/lib/package-card.js
> +      this.refs.avatar.src = `file://${path.join(process.execPath, "..", "resources", "pulsar.png")}`;
The app layout is different on different OSes. So, this wasn't working for me on macOS.

<details>

For me this resolved the following way (when run from my Documents folder temporarily for testing, but the same applies generally):

```
Users/User/Documents/Pulsar.app/Contents/Frameworks/Pulsar%20Helper%20(Renderer).app/Contents/MacOS/resources/pulsar.png:1
GET file:///Users/User/Documents/Pulsar.app/Contents/Frameworks/Pulsar%20Helper%20(Renderer).app/Contents/MacOS/resources/pulsar.png net::ERR_FILE_NOT_FOUND
```

It was looking effectively within the Renderer Helper app within the overall Pulsar app.

</details>

Instead, for a cross-platform way to get the resources path, we can do, from the [Electron APIs](https://www.electronjs.org/docs/latest/api/process#processresourcespath-readonly):

```suggestion
      this.refs.avatar.src = `file://${path.join(process.resourcesPath, "pulsar.png")}`;
```

Or, if concerned about future sandboxing stuff, since I think `process.resourcesPath` isn't provided to sandboxed renderer processes, we can use an Atom-specific (Pulsar-specific) API that will have to be provided some way or other to packages, sandboxing or not.

```suggestion
      this.refs.avatar.src = `file://${path.join(atom.packages.resourcePath, "..", "pulsar.png")}`;
```

(Since `atom.packages.resourcePath` resolves to ....`Resources/app.asar`, we need to do the `..` thing.)

(I don't think we'll ever be _required_ to enable sandboxing, per docs, and given how much disruption it would cause, I might assume we likely won't? https://www.electronjs.org/docs/latest/tutorial/sandbox. So, this is probably a moot point and the former should be valid. But both options are quite similar.)

This second option should work even with sandboxing, at the cost of being slightly more verbose.

2023-09-15 05:34 UTC, DeeDeeG submitted a review, later dismissed

2023-09-15 05:40 UTC, confused-Techie commented on packages/settings-view/lib/package-card.js
> +      this.refs.avatar.src = `file://${path.join(process.execPath, "..", "resources", "pulsar.png")}`;
@DeeDeeG Great catch on this error for cross-platform behavior!

I didn't catch that, as the resource I referenced to build this path was used only on Windows, I had wrongly assumed it was already cross platform, not at the time considering it only had to work on Windows.

So I'll go ahead and utilize `process.resourcePath` here as that seems like a great solution to me!

2023-09-15 05:43 UTC, confused-Techie commented
@DeeDeeG So I personally like our icon that's in use here more, a while ago I intended on actually using the icon from within the app (Which I think is essentially our semi-official icon) Or at least it's used in the majority of places.

So while I do prefer this one, I do agree it gets a bit "crunchy". So if we would rather use a properly scaled icon, we can ensure that this icon will [always](https://github.com/pulsar-edit/pulsar/blob/master/packages/settings-view/styles/package-card.less#L197) be `24px x 24px`. So we could potentially offer an optimized version if we would like.

Although I wouldn't be against packaging the GitHub org icon within our binaries themselves, if we think we would prefer it

2023-09-15 05:53 UTC, DeeDeeG commented
I don't want to get too stuck on the aesthetics thing if this saves us a large amount of backend resource usage. I think it's fair to come back to this icon eventually.

Maybe as a follow-up thing, we can run a quick poll -- since it's an aesthetics thing and not too hard to grasp/little context needed, might be the kind of thing that'd be easy to poll about.

2023-09-15 05:58 UTC, DeeDeeG commented
I noticed the download cloud icon doesn't make a ton of sense with no download count, so if we can find a way to remove that when not showing a count, that'd be neat.

Might start to be another thing that'd be good as a follow-up task, I kind of leave the scope of this up to your discretion, personally? Others might press harder on the design faux-pas of "indicating something without indicating something" -- a potential source of user confusion, and might be perceived as a lack of polish.

So it's down to, "how serious is design stuff, anyway??" (And I'd plop a code suggestion down if I had found where to change this yet. Probably in a different file?)

2023-09-15 06:08 UTC, confused-Techie commented
@DeeDeeG As you know, I'm not very design oriented. So I'd be very happy with leaving the results of iconography up to a poll, and for the meantime we go with the change as it currently is. 

As for the cloud showing with the download count, I do agree it's confusing, but this isn't behavior I've created. There was already a logic flow to not show a download count, which is used for packages that are locally installed, or if Pulsar is unable to reach the package backend. We just add the other if to say if this is a package that's from core. So this behavior of the empty cloud icon isn't new. We are just using it as more than a fallback.

In which case I do agree it's probably best to not show it at all, but being honest, I think we'd either have to optionally display it based on our assigned download count, or otherwise move the logic of creating that part of the display into the same code that adds the download count to the text. No matter what meaning it's a bit more of a change.

I'd be happy adding this as a followup, but with time needed on design issues I'm not sure I could get it done prior to a new release going out. But if we do think it gives to much a sense of imperfection or bad behavior, I'd be willing to wait for this PR to be merged for that behavior.

2023-09-15 06:24 UTC, DeeDeeG commented
Oh, okay. Well, that explains something. Sorry to report this, for me I think it's only "not hitting the API" for locally installed `ppm link`ed or "`ppm install`ed from a git URL" packages.

The rest of my bundled core packages get the GitHub org icon, And even when I rename my cache dir, it is repopulating the cache entries and fetching the GitHub org icon again.

I only confirm the PR's intent working for my two `ppm link`ed packages I was hacking on.

2023-09-15 06:31 UTC, confused-Techie commented
> Oh, okay. Well, that explains something. Sorry to report this, for me I think it's only "not hitting the API" for locally installed `ppm link`ed or "`ppm install`ed from a git URL" packages.
> 
> The rest of my bundled core packages get the GitHub org icon, And even when I rename my cache dir, it is repopulating the cache entries and fetching the GitHub org icon again.
> 
> I only confirm the PR's intent working for my two `ppm link`ed packages I was hacking on.

Well that is rather disappointing. If I had to guess `this.pack.repository` doesn't contain the raw string of the repository for our core packages like I'd hoped.

I'll have to take another look at this, and hope we can get it in in time. Otherwise if we can't, at the very least we will be able to properly touch on some of the other aspects we care about here. Thanks for letting me know

2023-09-15 06:37 UTC, DeeDeeG commented
`this.pack.repository: [object Object] did not match atom.branding.urlCoreRepo: https://github.com/pulsar-edit/pulsar`

It's returning the object form, I reckon.

So there should be some convenience function somewhere to grab the `repository.url`, or else we can write one without too much trouble if `typeof this.pack.repository === 'object'` or something like that.

2023-09-15 06:39 UTC, confused-Techie commented
> `this.pack.repository: [object Object] did not match atom.branding.urlCoreRepo: https://github.com/pulsar-edit/pulsar`
> 
> It's returning the object form, I reckon.
> 
> So there should be some convenience function somewhere to grab the `repository.url`, or else we can write one without too much trouble if `typeof this.pack.repository === 'object'` or something like that.

Great find! There is already a helper function `ownerFromRepository()` but that only returns the owner, so I can make another helper that does what we describe here, to ensure we are always getting the repository. Super awesome, I'll make that change in just a moment

2023-09-15 06:45 UTC, confused-Techie commented
And done, lets see if that does it

2023-09-15 06:50 UTC, DeeDeeG commented
Argh, it's adding `.git` at the end???

`this.pack.repository, JSON.stringify()ed, is: {"type":"git","url":"https://github.com/pulsar-edit/pulsar.git"}`

Anyhow, that's the format it's giving. All the bundled packages show similar in my `console.log()s`. (Sorry I assumed it would be the same as in their `package.json`s without the `.git` at the end.)

2023-09-15 06:57 UTC, confused-Techie commented
> Argh, it's adding `.git` at the end???
> 
> `this.pack.repository, JSON.stringify()ed, is: {"type":"git","url":"https://github.com/pulsar-edit/pulsar.git"}`
> 
> Anyhow, that's the format it's giving. All the bundled packages show similar in my `console.log()s`. (Sorry I assumed it would be the same as in the packages' `package.json`s, as in "without the `.git` at the end.")

So did I. Later on I'll have to look into exactly how this is generated, since that just seems so odd. But we can work with that, just a sec lol

2023-09-15 08:20 UTC, Spiker985 commented
Not a discussion for this change, but on the note of "crunchy" icons, (being that it is very late in the evening/very early in the morning and not from my computer) do we not ship an svg?

I know for a fact we ship a png, or collection of icons. But arguably, we could (and should, if we already don't) ship the svg due to linux at the very least.

That would be a much better resource to use a static call to, as svgs are natively scalable due to their vector nature

2023-09-15 14:28 UTC, confused-Techie commented
@Spiker985 So looking at our [`electron-builder` config](https://github.com/pulsar-edit/pulsar/blob/master/script/electron-builder.js) we do in fact ship an SVG icon on Linux only.

So in the long term you are totally right, that instead of serving variations of the same icon, at least in usage like this we should just provide an SVG.

2023-09-15 15:41 UTC, DeeDeeG approved these changes
It's working!

https://github.com/pulsar-edit/pulsar/assets/20157115/02252fbe-2e2d-4eb2-88f7-db76d4cf4188

I do see a mix of logos, mostly the `resources/pulsar.png` (white pulsar logo on a purple circle background, kinda cronchy), three packages with the GitHub org logo (purple pulsar logo with no background), and one Atom org logo as before.

And packages installed from git will of course use the org/account avatar from their respective repositories, assuming the repo isn't our core repo URL, which generally it wouldn't be.

Comfortable merging this on the technical basis, style questions aside for a later time.

2023-09-15 18:44 UTC, Spiker985 commented
Do we want to get this merged for 109, and open a follow-up issue for additional adjustments?

2023-09-15 19:42 UTC, DeeDeeG commented
Would love to see this merged for 109, I fully intend for it to be included, personally.

And then for a separate GitHub issue about the design + style stuff, I might lose track of the discussion in an issue, personally, and I was gonna open another thread on `#pulsa-core` on Discord for it?

2023-09-15 19:46 UTC, Spiker985 commented
Oh, seeing how this is 42 commits behind - should we get it up to date just to make sure something didn't break it in those 42 commits - then if it succeeds: merge for 109?

2023-09-15 22:51 UTC, confused-Techie commented
@Spiker985 I think we are still good to merge on this one, as I'm pretty sure the only thing merged between when I created the branch and now was the August Tree Sitter fixes. So nothing that should effect us here. Unless you wanted to be sure we could, otherwise, would love to get this in for 109, and we can then later focus on design aspects

2023-09-16 02:47 UTC, merged