Fix white-space issue
pulsar-edit/pulsar pull request #74
Opened 2022-09-28 01:44 UTC by softcode589

### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change
Fixes the white-space occurring due to some `<br>` tags in place.

### Release Notes
N/A

2022-10-02 00:35 UTC, icecream17 approved these changes

2022-10-03 23:29 UTC, Daeraxa commented
Is the space not just being left to make room for a new banner once we get the updated branding? Then the `![Banner]` just gets uncommented and a new link created for `[Banner]`.

2022-10-03 23:33 UTC, kaosine requested changes

2022-10-03 23:33 UTC, kaosine commented on README.md
> -
Just comment this section out, I should've done it originally instead of what I did since I was only concerned with removing the image.

2022-11-15 01:58 UTC, confused-Techie commented
@pulsar-edit/documentation What do we say we either close this PR or merge it. Since really we could go ahead and add the whitespace back in if/when we get our new logo. Since it seems that may take some time, and it'd be nice to clean up as many PR's as we can

2022-11-15 02:08 UTC, Daeraxa commented
I think this is probably going to be lost in that other PR that somebody is submitted for the readme redesign?

2022-11-15 02:12 UTC, confused-Techie commented
> I think this is probably going to be lost in that other PR that somebody is submitted for the readme redesign?

You are right that that PR modifies the changes present here. But since it isn't the fault of softcode that a newer PR undos their changes, what do you say we merge this one, then review PR #123 more closely

2022-11-15 02:27 UTC, Daeraxa commented
Oh didn't mean it like that, if the changes that were requested aren't really still desired then I say go ahead and merge it.

2022-11-16 02:08 UTC, confused-Techie commented
Alright, so to back up @kaosine here and their requested changes. Since this PR has had requested changes for over a month that have not been addressed, in accordance with our [Contributing Guide](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md), we are going to have to go ahead and close this one.

Thanks for the contribution as always.

2022-11-16 02:08 UTC, closed without merging