Update readme.md links to new site
pulsar-edit/pulsar pull request #83
Opened 2022-10-03 23:35 UTC by Daeraxa

Links lead to the repo docs, now the new site is live we can redirect the buttons to the general docs section, the installation section (which is yet to be completed) and the the build instructions.

This will clash with #81 and #74 (if the latter is to be merged) but both are easy conflicts to resolve.

2022-10-04 17:39 UTC, kaosine requested changes

2022-10-04 17:39 UTC, kaosine commented on README.md
>  <!---------------------------{ Files }--------------------------->
Probably should change this line but otherwise looks good!

2022-10-07 16:33 UTC, kaosine commented on README.md
>  <!---------------------------{ Files }--------------------------->
@Daeraxa update on this, maybe?

2022-10-07 18:38 UTC, Daeraxa commented on README.md
>  <!---------------------------{ Files }--------------------------->
Sorry missed this. What, just rename it to links or something?

2022-10-07 18:40 UTC, kaosine commented on README.md
>  <!---------------------------{ Files }--------------------------->
Yea, links would be the ideal one yes

2022-10-07 19:10 UTC, Daeraxa commented on README.md
>  <!---------------------------{ Files }--------------------------->
Links was already being used so renamed to Documents which can be for both website links and repo files if necessary.

2022-11-03 02:58 UTC, Spiker985 commented on README.md
>  [Retired]: docs/Retirement.md 'Check out what happened to the original Atom project.'
```suggestion
[Retired]: https://github.blog/2022-06-08-sunsetting-atom/ 'Check out what happened to the original Atom project.'
```

2022-11-03 02:59 UTC, Spiker985 requested changes
Added link to GitHub sunset blog post from https://github.com/pulsar-edit/pulsar/pull/108/

2022-11-03 03:01 UTC, Spiker985 commented
This should also close #64 when merged

2022-11-03 03:04 UTC, Spiker985 approved these changes

2022-11-03 03:06 UTC, Spiker985 commented
@kaosine Since I don't have write access, I can't approve the PR to allow it to show it's merge status. You mind taking a look, and hopefully approving?

2022-11-03 03:19 UTC, Daeraxa commented
I sync'd the branch to include your commit from #81 so that shouldn't cause a merge issue now, it was still pending when I made this PR.

2022-11-03 04:26 UTC, confused-Techie approved these changes
Since I managed to miss it the first time, here's my approval.

Looks great, and I'll go ahead and remove @kaosine's changes since they seem to be addressed, and you are wanting to check the merge status.

2022-11-04 22:35 UTC, confused-Techie commented
Alright, this PR has been active for over a month.

Since I've already approved it, and it is a non-code changing PR, meaning we only need one approval, I'll go ahead and merge.

Thanks for the contribution!

2022-11-04 22:35 UTC, merged