CI: build Linux x86-64 binaries on older Linux
pulsar-edit/pulsar pull request #858
Opened 2024-01-13 16:20 UTC by DeeDeeG

### Issue or RFC Endorsed by Atom's Maintainers

Resolves https://github.com/pulsar-edit/pulsar/issues/733
Resolves https://github.com/pulsar-edit/pulsar/issues/747

### Description of the Change

**Short summary:** Build Pulsar's Linux x86-64 binaries on an older version of Linux, in a Docker container. Appears to allow older Linux distros (with older glibc) to run Pulsar.

**Details:**

This gets us building against older glibc, which is forward-compatible with modern distros (great) but also compatible with contemporaneous distris from when that older glibc was the latest (notable older Red Hat Enterprise Linux and RHEL-alike distros, which have very long support windows and don't update their glibc within a major distro version.) This compatibility with RHEL-alike distros is the main purpose of this PR. See the above-linked issues for context and the requests from users for this change.

I also added a _separate_ job that waits for the build job to finish, that will _extract and test_ the built Linux binaries in a normal `ubuntu-latest` GitHub Actions runner environment (that is: outside of any Docker container). I wasn't able to get the tests to run (playwright couldn't successfully launch Pulsar in the Docker container -- ???), so this added complexity is the cost of still doing the integration (visual editor) tests on Linux. 

(Tangent: Since the macOS visual editor tests may or may not even be running, I think this is the only way we run the visual tests at all. I like the visual tests! We should keep running them. I wish I could figure out how to do so in Docker, but it wasn't working for me. I'm not sure whether Playwright has ever played nice with Debian 10 or Docker, since Debian 11 support was the first time Playwright's release notes mentioned any deliberate Debian support. Oh, well.) 

### Alternate Designs

Could build on an even _older_ Linux distro, for compatiblity with such _older_ distros, but I would rather keep it to fully first-party officially supported distros, personally. It's easier for us to deal with distros during the build that are fully supported, than mess around with separate LTS infrastructure you have to opt-into. See this discussion for some context and my thoughts when asked about building for _even older_ Debian: https://github.com/pulsar-edit/pulsar/issues/733#issuecomment-1766739333

On another note: I would really like to run the tests in the same Docker container the binaries are built on. So we don't need _two_ separate jobs just to build (1) and test (2) the Linux binaries. But I couldn't get testing working within the Docker container (job 1) so I needed a second job (job 2) outside the Docker container.

### Possible Drawbacks

I don't feel qualified to assess what building on older distros would do for the binary -- maybe slightly less optimization in the native C/C++ code, due to older glibc and older compiler stack? But we're a mostly JS stack, so unclear how much this would even matter if true.

I expect any difference would not be noticeable to end-users. Could be wrong, honestly.

### Verification Process

Foks on older distros tested binaries generated this way, and it worked for them:
- https://github.com/pulsar-edit/pulsar/issues/733#issuecomment-1728645942
- https://github.com/pulsar-edit/pulsar/issues/733#issuecomment-1764766927

### Release Notes

Build Linux binaries on Debian 10, for older glibc and compatibility with older Linux distros

2024-01-13 16:26 UTC, DeeDeeG commented
I could easily squash some of these commits, but, on the other hand, this commit log shows (some of) the journey I went through trying to get this working and still run our tests.

2024-01-16 19:10 UTC, DeeDeeG commented
Update: The commit log showing all the things I had to try to get here is at https://github.com/DeeDeeG/pulsar/tree/CI-build-on-older-Linux-v1 (current tip of that branch is commit 21ad8e3d79a5bf1e15fccd6a8f23e5b9058d8229).

I'll be squashing this PR's branch so the commit history here is neater, but anyone curious about why I implemented this this way can check the things I tried in the commit history of that original branch.

2024-01-18 15:53 UTC, confused-Techie requested changes
Overall this looks fantastic!

A seriously impressive amount of CI wizardry is stuffed into this change.

Overall everything seems to be doing exactly as advertised which is awesome, and the only questions/requests I have are very minor, so feel free to disagree if you feel the need.

Firstly, it might be a good idea to comment at the top of `test-and-upload-Linux` just to quickly document the reason it exists outside of the regular run, just so we can quickly remember it's a visual test issue. 
Secondly, I would wish we can keep our single declaration for Python versioning. Since by removing the Python action and having Python stuffed into the larger `Install build dependencies - Linux` command, I feel like it sorta gets lost.

Think there's anyway we could utilize the environ values to specify the version still, maybe by utilizing that to construct the install command? Or I think I'd feel better with just creating a `Setup Python - Linux` where we can run the ap install. But what do you think?

---

Sorry the review has taken so long, thanks a ton for this one

2024-01-25 04:50 UTC, DeeDeeG commented
> Firstly, it might be a good idea to comment at the top of `test-and-upload-Linux` just to quickly document the reason it exists outside of the regular run, just so we can quickly remember it's a visual test issue.

Good idea, done!

> Secondly, I would wish we can keep our single declaration for Python versioning.

I added a comment to explain why I had to not do that. Debian 10 is _old_. Old enough that software built with newer glibc won't run on it, ergo this PR to get _Pulsar_ running on older Linux. The copy of Python we'd get from `actions/setup-python` is _also_ compiled against too new glibc to run on Debian 10.

Getting newer Python on older Debian is kind of a pain, so I just let the Linux build use Python 3.7 (!!!) as the latest version available from Debian 10 "Buster"'s package repos: https://packages.debian.org/buster/python3. Alternative would be to maybe use a PPA like deadsnakes. https://unix.stackexchange.com/a/188819. Kind of a pain and not worth it, IMO, personally.

2024-01-26 02:00 UTC, confused-Techie approved these changes
@DeeDeeG Thanks for addressing my concerns! This looks awesome from here, and I think we are good to get it merged!

2024-01-29 06:17 UTC, merged

2024-01-29 23:58 UTC, Charadon commented
Hey, just wanted to mention. Since this is based on Debian 10, and Debian 10's main support ends in June. Don't forget to add the Freexian repositories for extended support when that time comes: https://www.freexian.com/

It's officially supported by Debian themselves.