Bundle snippets
pulsar-edit/pulsar pull request #993
Opened 2024-04-28 20:24 UTC by confused-Techie

Like many PR's that have come before it, this PR bundles snippets right into the main repo.

This PR was kept at bay due to some open PRs on the snippets repository, but as discussed in #972 those PR's have now been merged, and we are good to go ahead and bundle snippets.

Once bundled, I'll update #512 as well as bring the two existing issues on the snippets repository over to this repo, then of course archive the original snippets repository.

The only changes that have occurred are present within the second commit, the first commit simply copied the contents of the snippets repository over.

2024-05-06 06:32 UTC, savetheclocktower commented
> For some reason the Editor Tests here are failing. The only big difference I can tell for these runs as compared to previously successful runs is a difference in NodeJS versions.
> 
> This run used `v16.20.1` meanwhile the last successful run used `v16.20.2` while a very small difference, it's the only thing obvious I can find. As for why this run went back a version, it looks like NodeJS was removed from the base image, since previously it was always found in the base image's cache. So without it being found I suppose it automatically downloaded it, and for whatever reason didn't grab the most up to date version. I'll test out specifying an exact version of NodeJS

Now that @DeeDeeG has fixed the CI issues, a rebase from `master` should get this PR working, as it did on both of my open PRs.

2024-05-06 08:00 UTC, confused-Techie commented
Alright this one is ready for review, like @savetheclocktower pointed out with the CI bump it's almost totally passing. The only thing failing here is Codacy, which I think we have all decided doesn't matter in terms of merging a PR. (And in general should have a limit to avoid ever failing on a PR, but with so much code makes sense now is when it happens.)

2024-05-06 20:09 UTC, DeeDeeG approved these changes
Yeah, Codacy has some fair points about defined but unused vars/functions, but nothing too drastic I don't think.

I am mostly trusting that this bundling was done as intended, actual specs appear to be green/passing. 👍


So, "rubber stamp / specs are passing approve" from me!

If we're done with the PEGjs files, some manual cleanup of the generated JS might be worthwhile, if anyone gets the itch to do some code cleanup. Codacy may well be a decent reference for this purpose. Not a blocker IMO.

2024-05-06 20:14 UTC, DeeDeeG requested changes
Tiny markdown fixes?

2024-05-06 20:14 UTC, DeeDeeG commented on packages/README.md
> +| **snippets** | [`./snippets`][./snippets] |  |
```suggestion
| **snippets** | [`./snippets`](./snippets) |  |
```

Quick markdown link syntax suggestion.

2024-05-06 20:14 UTC, DeeDeeG commented on packages/README.md
> +| **symbols-view** | [`./symbols-view`][./symbols-view] |  |
```suggestion
| **symbols-view** | [`./symbols-view`](./symbols-view) |  |
```

Quick suggestion. I don't think the double square brackets were valid before, but now I'm second-guessing myself?? I'll look up some docs... Posting this now so it doesn't get missed since I already a pproved a second ago!

2024-05-06 21:01 UTC, savetheclocktower commented
Most of the Codacy suggestions have to do with it not realizing that the spec files run in a spec environment. That one might be as simple as an `.eslintrc.js` in the `spec` directory matching the ones we already have in the repo for other packages' `spec` directories.

2024-05-07 14:42 UTC, confused-Techie commented
@DeeDeeG Thanks for catching the now invalid Markdown, I've merged your fixes.

But @savetheclocktower it looks like you're right about the specs being a major cause of Codacy being unhappy, so glad to see it shouldn't be too much of a pain to fix.

Otherwise once CI is passing if DeeDee's approval still applies we can go ahead and merge this one.

2024-05-09 00:05 UTC, merged